### ISSUE TITLE
Activities Import through CSV (simplified)

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#1]
In Aidstream, organisations should be able to upload their activities through csv. There will be template the organisations has to fill their activities and then upload in the system. There will be two types of template - simplified (which contains the basic and mandatory fields only) and complete (which contains all the fields). This issue covers only the simplifed csv import only. 
### Fields

The following fields will be included in the CSV template
- identifier
- title
- description-general
- description-objectives
- description-targetgroups
- description-other
- planned-start-date
- planned-end-date
- actual-start-date
- actual-end-date
- status
- country
- region
- funding-organisation
- implementing-organisation
- sector

The simplified includes the headers such that codelist are already included like for description, activity-date, participating-organisations. The validation will be in-placed such that one of the 4 descriptions are present for the activity to be valid.
### Validation

The following validation rules will be in-placed
- activity-identifier
  -  compulsory, will be concatenated with the reporting-org-id to generate iati-identifier. This can't be duplicated in the given file. If the id is already present in the system, aidstream will prompt users whether to update the activity or ignore it.
- title
  - compulsory 
- description-general
- description-objectives
- description-targetgroups
- description-other
  - one of the four descriptions is compulsory. Based on the description, decription-type will be assumed and imported into the system
- planned-start-date
- planned-end-date
- actual-start-date
- actual-end-date
  - One of the four dates is compulsory. It checks whether the start-date is less than end-date.
- status
  - should be one of the codes (1-6) from the codelist http://iatistandard.org/201/codelists/ActivityStatus/
- country
  - should be country code from the codelist. If more than one, the multiple codes should be separated by semicolon
- region
  - should be region code from the codelist. If more than one, the multiple codes should be separated by semicolon
- funding-organisation
  - list of funding-organisation names. If more than one, should be separated by semicolon
- implementing-organisation
  - list of implementing-organisation names. If more than one, should be separated by semicolon
- sector
  - list of sector codes (assuming 5 digits DAC codes). If more than one, should be separated by semicolon.

**Comment by anjesh** [comment]
The following process is to be followed during the Activities CSV upload process
1. Upload the CSV file as per template
2. Validate the file if the template is followed, if the appropriate codes are used, if the data is valid
3. If not valid, show the error message with the row number that has the error
4. If valid, check if the identifiers are already included in the organisation's database
5. Insert the new activities row (for which identifiers don't exist in the database)
6. If the identifiers exists, show a page with the list of existing activities (with the checkboxes)
7. The user will tick the check-boxes for those activities which s/he wants to update. Unchecked activities will not be updated in the system.

**Comment by geshan** [comment]
The task seems quite big :confused: can it be broken in to smaller parts if possible.
