### ISSUE TITLE
Error message appearing

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#100]
Whilst supporting a publisher to set up their AidStream account, AidStream kept showing an error message 'something went wrong' when trying to verify their publisher ID or select the API field. When updating the activity elements checklist, the page would not save any changes.

The publisher was using a Windows Explorer 10 as their browser.

At the same time, my account was working and I could make the changes.

Any ideas on how to solve this one?

**Comment by shresthaKiran** [comment]
Dear Amy,

Could you please provide us the name of the organisation in which this issue was faced.

**Comment by amy-silcock** [comment]
Hi Kiran,

It was Oxford Policy Management

**Comment by sachit-singh** [comment]
Dear Amy,

Your Default Values had not been saved. I have set US Dollar as the default currency and English as Default Language for your account. You will be able to change then under the Default Values settings. Could you please try uploading the activities again and tell us if you face any problems.

We apologize for the inconvenience and the late reply and appreciate your understanding.

Sachit.

**Comment by amy-silcock** [comment]
Dear Sachit,

Is this in response to issue #99 and uploading activities via CSV import?

I have tried uploaded the file again and get the same error message ‘404 – something went wrong’.

I am doing this on my ‘test’ account attached to amy.silcock@devinit.org<mailto:amy.silcock@devinit.org>. In preparation for supporting OPML to import their data across.

With regards to issue #100

Please can you get in contact with Oxford Policy Management to resolve this issue.

Thank you


Amy Silcock I IATI Business and Data Analyst
Development Initiatives, North Quay House, Quay Side, Temple Back, Bristol, BS1 6FL, UK
T: +44 (0) 1179 272 505 I Skype: amy.silcock.devinit.org
devinit.org<http://www.devinit.org/> I @devinitorg
Sign up<http://devinit.org/#!/about/newsletter-sign-up> to our newsletter and topic updates

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives.  If you have received this email in error, please delete it and notify the sender.

**Comment by sachit-singh** [comment]
Hi Amy,

I have sent an email to Kevin Carr on your request. But I did not see any problems regarding the publisher id and api key because they have already been configured correctly.

In regards to [Issue#99](https://github.com/younginnovations/aidstream/issues/99), the organisation associated with the email 'amy.silcock@devinit.org' is named SilcockTest which has been registered for the Lite(minimalistic) version for AidStream, for which the CSV Import feature is not present. Are you sure that this *is* the account you tried uploading the data into. I am a bit confused here. Can I ask how did you manage to upload the file after which you got the error? 

Also, could you please send us the file you were trying to upload.

Best Regards,
Sachit

**Comment by amy-silcock** [comment]
Hi Sachit,

With Kevin Carr's account, AidStream kept crashing when he tried to enter the details or change the settings. I gather AidStream are currently in contact directly with Kevin about this? The IATI tech team ended up entering the API and publisher ID for him whilst doing 1:1 support as Kevin's system would not allow him to do so.

I have two accounts - one for the full version and one for trying out the Lite version of AidStream. The e-mail address TEST@iatistandard.org is attached to the full version. It is on this one that I have been trying to use the CSV Import feature. Sorry for the confusion there.

I will e-mail the file over to you separately.

Best wishes,

Amy

**Comment by sachit-singh** [comment]
Hello Amy,

The issue with the CSV Import has been resolved. Could you please confirm if its ok. However, Kevin has not replied to the email I sent.

Thank you.

**Comment by amy-silcock** [comment]
Hi Sachit,
Yes the activities that import can now be seen and edited.

However, 5/7 activities are now showing an error saying that the 'ACTUAL START DATE OR PLANNED START DATE SHOULD BE BEFORE ACTUAL END DATE OR PLANNED END DATE.'

I can't see that this is the case on the CSV file:

![image](https://user-images.githubusercontent.com/27764077/27385817-bac8e026-568b-11e7-9d8f-9073196c750b.png)

**Comment by sachit-singh** [comment]
Hello.

The problem was our date format was rejecting the dates that you had entered. But the issue with the dates has been solved. Could you please check and confirm? Thank you Amy.

**Comment by amy-silcock** [comment]
Thanks Sachit, it is now working!

**Comment by sachit-singh** [comment]
You're welcome.
