### ISSUE TITLE
Error accepting 0 as indicator value, and wrong error message

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#101]
I think this is an error in handling a zero value (maybe similar to #95?):

if I add a target of 0, with a comment, I get an error message. If I change the target value to 1, it is accepted.

(1) value 0 not accepted

(2) the error message seems to the wrong one?

By the way: since the dimension fields are marked in red as well, a user can easily conclude that something needs to be filled in here as well, leading to dimension values like "-" or "n/a".

![2017-06-15_01](https://user-images.githubusercontent.com/223935/27173023-940b2954-51b7-11e7-9ab2-9970f389cf58.png)

**Comment by sachit-singh** [comment]
Hi Rolf,

This has been solved. Could you please confirm.

Thank you.

**Comment by rolfkleef** [comment]
Thanks, works now!
