### ISSUE TITLE
Add hint to "Add more" links

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#102]
It's usually hard to guess for a user which "Add more" link they need, especially with the results/indicators. Would it be possible to add a hint to the link, so that a little title pops up to show what will be added? Or better: to rephrase the link in "Add another indicator", "Add another narrative", etc?

![2017-06-15_03](https://user-images.githubusercontent.com/223935/27181803-73884abe-51d9-11e7-8c3d-5783ac504443.png)

**Comment by 77karuna** [comment]
Hi Rolf,

This enhancement has been added to the Result element.

Thanks.

Regards,
Karuna
On behalf of AidStream Team
