### ISSUE TITLE
Entry 1-1 removed from HumanitarianScopeVocabulary CodeList, which has been used.

### ISSUE THREAD

**Issue by sachit-singh** [younginnovations/aidstream#105]
In the [HumanitarianScopeVocabulary](http://iatistandard.org/202/codelists/HumanitarianScopeVocabulary/) codelist, the entry _1-1 UN OCHA FTS_ was removed. But it has been used in AidStream with around 4 activities published to the IATI Registry. How can this be tackled?

All the activites are for [Cordaid](https://iatiregistry.org/publisher/cordaid) for which  _1-1 UN OCHA FTS_ HumanitarianScopeVocabulary is used, under the same [Activity XML file](https://aidstream.org/files/xml/cordaid-activities.xml) and the titles listed below:

- [Cordaid - Afghanistan Joint Response - AFJR](https://aidstream.org/files/xml/cordaid-activities.xml)
- [DRA Joint Response Ukraine - 2](https://aidstream.org/files/xml/cordaid-activities.xml)
- [Afghanistan Joint Response - AFJR](https://aidstream.org/files/xml/cordaid-activities.xml)
- [DRA South Sudan Joint Response 2](https://aidstream.org/files/xml/cordaid-activities.xml)

**Comment by anjesh** [comment]
Sachit, can you also paste the list of activities title with link to their XML file here? thanks.

**Comment by andylolz** [comment]
Yeah true, it was removed here:
https://github.com/IATI/IATI-Codelists-NonEmbedded/commit/5d5eebb8

But this seems like a question for @dalepotter / @wendyrogers… Shouldn’t this code have been marked as `withdrawn` rather than removed?

**Comment by andylolz** [comment]
Here’s the discussion about the removal:
https://discuss.iatistandard.org/t/resolved-remove-entry-1-1-from-humanitarian-scope-vocabulary/674

So while removing the code [seems to go against the practice described on the standard website](http://iatistandard.org/202/codelists/codelist-management/#code-status-addition-and-withdrawal-dates), I wonder if it might be better to just encourage Cordaid to update these 4 activities.

It looks like the relevant codes using vocab `2-1` are:

 * `HAFG16` (Afghanistan 2016)
 * `HSSD16` (Republic of South Sudan 2016)
 * `HUKR1615` (Ukraine 2016)

**Comment by sachit-singh** [comment]
We were just thinking the same thing about it. Thank you @andylolz for the PR and this. :)
