### ISSUE TITLE
Error with Activity IDs

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#108]
Hi all,

I've noticed on Palladium's activities that the ID's start with GB-CHC-123456

![image](https://user-images.githubusercontent.com/27764077/28315723-a4f31730-6bb7-11e7-89d2-aebf9c0ade39.png)

I can't see where this is coming from and don't think it should be included.

Can you take a look?

Thank you, Amy

**Comment by sachit-singh** [comment]
Hello Amy, 

It seems that the Activity Identifier for the activity concerned for Palladium is '-COH-2394229-BDSEP', where as it should have been 'BDSEP' only. I have attached a screenshot below.

Once the activity identifier is updated, then the correct activity identifier will appear.

![palladium](https://user-images.githubusercontent.com/8382151/28316796-ecfd60e0-6be3-11e7-9db9-0c9dc671c602.png)

**Comment by sachit-singh** [comment]
But the activity needs to be published once again.

**Comment by amy-silcock** [comment]
Thanks @sachit-singh!

**Comment by sachit-singh** [comment]
No problem @amy-silcock !
