### ISSUE TITLE
New Humanitarian Elements & Sector Vocabs Missing From V2.02

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#11]
I have updated my organisation (demo) to V2.02. However I don't appear to have the option to use the new v2.02 humanitarian elements:
humanitarian scope - http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/humanitarian-scope/
@humanitarian attribute on iati-activity - http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/

Also sector vocabulary dropdown does not include the vocabularies added at v2.02 nos 7 to 10 see - http://iatistandard.org/202/codelists/SectorVocabulary/

**Comment by sachit-singh** [comment]
To use the Humanitarian elements, one needs to check the Humanitarian Scope element on the [settings page](http://newstage.aidstream.org/settings) for the particular organization, which, by default is unchecked (on version 2.02). 

The @humanitarian attribute has already added on iati-activity and is set to false by default on version upgrade.

Also, the missing sector vocabulary codes have also been already added.
