### ISSUE TITLE
Confusion over organisation name in transactions

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#110]
I got a question about the provider and receiver organisation in a transaction: the user entered the organisation and activity identifiers, so technically that's sufficient.

The view of the transaction suggests that the provider and receiver organisation are not available, which leads to confusion:
![2017-07-20_01](https://user-images.githubusercontent.com/223935/28424784-cf302bb0-6d6e-11e7-9546-87b623b39533.png)

It would be clearer if that said "No name available" or "No name entered" or something similar.

**Comment by sachit-singh** [comment]
Dear Rolf,

The issue has been fixed. Could you verify from your end. Thank you.

**Comment by rolfkleef** [comment]
In my [test activity](https://aidstream.org/activity/10437/transaction/84216), the result still seems to be the same?
![2017-07-21_01](https://user-images.githubusercontent.com/223935/28465443-185306ae-6e29-11e7-9b2b-9c635653b082.png)

(Looking at the other fiels, something like "Name: not available" seems to be a good option.)

**Comment by sachit-singh** [comment]
Hello Rolf,

It has now been fixed. It seems that I had missed a file to update. Can you please verify from your end. We apologize for the inconvenience and appreciate your understanding.

Best Regards,
Sachit

**Comment by rolfkleef** [comment]
Thanks, works now!
