### ISSUE TITLE
Registration Agency - LR-MPEA

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#111]
Can the following registration agency please be added to AidStream:

**Code**: LR-MPEA
**Name**: Ministry of Planning and Economic Affairs
**Country**: Liberia
**Description**: The Ministry of Planning and Economic Affairs (Liberia) held responsibility for regulating the activities of Non-Governmental Organisations (NGOs). It issues a "Certificate of Accreditation" to organisations, which should be renewed every three years.

Thank you

**Comment by sachit-singh** [comment]
Hello Amy,

The mentioned registration agency has been added. Could you please verify. 

Thank you.

**Comment by amy-silcock** [comment]
Wonderful, thank you for adding this. I can confirm that it is here.

**Comment by sachit-singh** [comment]
You're welcom Amy.
