### ISSUE TITLE
Allowing multiple sector elements at transaction level

### ISSUE THREAD

**Issue by PetyaKangalova** [younginnovations/aidstream#114]
I just had a call with a publisher using Aidstream. They are publishing` sector` information at transaction level. According to the IATI standard `iati-activities/iati-activity/transaction/sector` the sector element can occur multiple times. See reference in [IATI activity summary table](http://iatistandard.org/202/activity-standard/summary-table/).

At the moment, Aidstream does not have this functionality (see below). Could this be fixed?

![image](https://user-images.githubusercontent.com/24607542/31286808-4026dbb8-aab7-11e7-912a-29837cc4b753.png)

Thanks,
Petya

**Comment by sachit-singh** [comment]
Thank you @PetyaKangalova for noticing. I don't know why, but it seems we might have missed this during developement. Is it okay if I inform you once I look into the necessary changes? Thank you once again Petya. Have a good day.

**Comment by PetyaKangalova** [comment]
@sachit-singh  Many thanks for the quick response and no problem at all. I am also cross-checking with @wendyrogers if there is any further guidance we need to provide before you implement any changes.  If you can wait until early next week that would be great. Many thanks again.

**Comment by sachit-singh** [comment]
Yes we can surely wait until then @PetyaKangalova. Thank you very much.

**Comment by PetyaKangalova** [comment]
@sachit-singh I have now checked and can confirm that multiple sectors are allowed, so could you please go ahead and implement the changes requested above? See [Activity Summary Table.](http://iatistandard.org/202/activity-standard/summary-table/) which shows that` sector` can occur multiple time 0...*  at activity `iati-activities/iati-activity/sector ` and
transaction `iati-activities/iati-activity/transaction/sector` level. This allows publishers to classify their data using different vocabularies.

Let me know if you have any other questions.

**Comment by sachit-singh** [comment]
Thank you @PetyaKangalova. I will let you know once it has been completed.

**Comment by sachit-singh** [comment]
@PetyaKangalova This has been deployed not. Could you please verify ? Thank you.

**Comment by PetyaKangalova** [comment]
@sachit-singh  Many thanks! I have now checked the functionality on Aidstream and can add multiple sectors.  I will inform the publisher I was working with so that they can start using it.

Thanks again!
