### ISSUE TITLE
Use of hierarchies

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#116]
Hi,

Can you please remove the option for publishers to select the default hierarchy level as greater than 1? This still allows publishers to override the hierarchical level for individual activities. There are a few instances where publishers are only publishing at levels 3, 4 and 5 etc. Or not they are not publishing sequentially.

This should help reduce the problem.

Thank you.

**Comment by sachit-singh** [comment]
Hello Amy,

Do you mean the override functionality for activities? Also, could you let me know about some of those instances where publishers are only publishing at levels 3 or more. Yes, it can be done, but I will have to check with its implications, with which you might be able to help.

Thank you Amy.

**Comment by amy-silcock** [comment]
Hi,

Not the override function but the initial setting of the default activity level:
![image](https://user-images.githubusercontent.com/27764077/31503243-0f511864-af67-11e7-9001-d19fce6899c4.png)
It would be good if this was always set at level one. Not many organisations are using hierarchies incorrectly. But this simple fix should prevent a few errors.

Then organisations can still override this for individual activities.

Three examples from organisations using AidStream are:
- Agência de Desenvolvimento do Vale do Zambeze (Publishing at level 5)
- SOS Children's Villages The Netherlands (Publishing at level 3)

Also, Anti-Slavery International and a few others are not publishing sequentially e.g. at levels 1 and 3. But this issue will be a harder one to solve.

**Comment by sachit-singh** [comment]
Thank you Amy. I will get back to you on this as soon as possible.

**Comment by sachit-singh** [comment]
Hi Amy,

By 'always setting the Default Hierarchy to 1', did you mean not letting the users change it (under settings) and only letting the users override the Default Hierarchy for Activities? Or can the users still change the Default Hierarchy for the Settings?

**Comment by amy-silcock** [comment]
First option - always setting the default hierarchy to 1

**Comment by sachit-singh** [comment]
Hi Amy,

The Default Hierarchy is now set to one. Users can only override them at the Activity level. Can you confirm this? And I have a question. What about the organisations that publishing at levels other than 1? They will not be able to change it to 1 now. How should we proceed with this?

**Comment by amy-silcock** [comment]
Thanks Sachit.

I can confirm that the change has been made. Could you please amend the description to correspond with the changes made?

I have contacted all the AidStream organisations who have published with a default value higher than 1. Can I l get you know if they get back to me and then ask you can change them individually? We can't change an organisation's data without their consent.

**Comment by sachit-singh** [comment]
Yes, sure thing Amy. Thanks.
