### ISSUE TITLE
minor: "2.0.2" should be "2.02"

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#12]
In the top-right corner there is an indicator telling me there is an "update available". The pop-up says to version "2.0.2", which should be "2.02"

![2016-03-03_01](https://cloud.githubusercontent.com/assets/223935/13497119/081a83f6-e154-11e5-90b2-547c43d566c7.png)

**Comment by sachit-singh** [comment]
This issue has already been fixed.
