### ISSUE TITLE
Activity IDs - allow more characters

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#120]
Hi AidStream,

Can you please amend the 'Organisation Registration Number' field under settings to allow a greater range of characters. It's decided that organisations should replicate their registration number as it appears on their certificate this can include '/', ':' etc.

![image](https://user-images.githubusercontent.com/27764077/33372095-bcaf3920-d4f4-11e7-89f7-4449aaee39ec.png)

**Comment by sachit-singh** [comment]
Dear Amy,

Now '/' characters have been allowed for the Identifier element. Could you please verify from your end. Apologies for the delay.

Sachit

**Comment by amy-silcock** [comment]
Dear Sachit,

That's great! I can confirm it is working. Please can the character : also be added?

Best wishes,

Amy

**Comment by sachit-singh** [comment]
Hi. The colon character(:) is also now allowed. Could you please confirm Amy?
