### ISSUE TITLE
old activity not deleted from registry

### ISSUE THREAD

**Issue by deepakt3** [younginnovations/aidstream#121]
We have deleted duplicate activity file from AidStream but it seems that it has not been deleted from the registry. Can you kindly look into this matter?
Our organisation identifier is XI-IATI-1002

Thank you

Deepak

**Comment by sachit-singh** [comment]
For the activity to be deleted on the registry, you will need to publish you data (an activity or activity xml file).

**Comment by deepakt3** [comment]
I have deleted the activity file. so how could I publish that that. please advise.


DEEPAK THAPA
Funds Management Officer  |  Funding Management Team
[http://www.umn.org.np/umn_signature/email-icon.png] deepak.thapa@umn.org.np<mailto:deepak.thapa@umn.org.np>  |  [http://www.umn.org.np/umn_signature/phone-icon.png]  +977 1 4228118 ext. 110<tel:+977%201%204228118>  |  [http://www.umn.org.np/umn_signature/mobile-icon.png]  +977 9841917554<tel:+977%209841917554>
[http://www.umn.org.np/umn_signature/sign_logo.jpg]<http://www.umn.org.np/>
[http://www.umn.org.np/umn_signature/f.jpg]<https://www.facebook.com/umnnepal>[http://www.umn.org.np/umn_signature/g.jpg]<https://plus.google.com/+UnitedMissiontoNepalKathmandu>[http://www.umn.org.np/umn_signature/t.jpg]<https://twitter.com/umnnepal>[http://www.umn.org.np/umn_signature/l.jpg]<https://www.linkedin.com/company/united-mission-to-nepal>[http://www.umn.org.np/umn_signature/y.jpg]<https://www.youtube.com/umnepal>[http://www.umn.org.np/umn_signature/bottom.jpg]



________________________________

**Comment by sachit-singh** [comment]
Dear Deepak,

In order to update the data in the IATI Registry, you would need to publish an Activity. In this case, you need to publish the remaining activity. I have published it on your behalf. Could you please confirm?

Best Regards,
Sachit

**Comment by deepakt3** [comment]
Dear Sachit ji,


Thank you for this. Please kindly  publish the file.


Regards,


Deepak

DEEPAK THAPA
Funds Management Officer  |  Funding Management Team
[http://www.umn.org.np/umn_signature/email-icon.png] deepak.thapa@umn.org.np<mailto:deepak.thapa@umn.org.np>  |  [http://www.umn.org.np/umn_signature/phone-icon.png]  +977 1 4228118 ext. 110<tel:+977%201%204228118>  |  [http://www.umn.org.np/umn_signature/mobile-icon.png]  +977 9841917554<tel:+977%209841917554>
[http://www.umn.org.np/umn_signature/sign_logo.jpg]<http://www.umn.org.np/>
[http://www.umn.org.np/umn_signature/f.jpg]<https://www.facebook.com/umnnepal>[http://www.umn.org.np/umn_signature/g.jpg]<https://plus.google.com/+UnitedMissiontoNepalKathmandu>[http://www.umn.org.np/umn_signature/t.jpg]<https://twitter.com/umnnepal>[http://www.umn.org.np/umn_signature/l.jpg]<https://www.linkedin.com/company/united-mission-to-nepal>[http://www.umn.org.np/umn_signature/y.jpg]<https://www.youtube.com/umnepal>[http://www.umn.org.np/umn_signature/bottom.jpg]



________________________________

**Comment by sachit-singh** [comment]
Dear Deepak,

The file has already been published.

**Comment by deepakt3** [comment]
Dear Sachit ji,


Thank you for your kind support. I will contact you if need more support.


with best regards,


Deepak


DEEPAK THAPA
Funds Management Officer  |  Funding Management Team
[http://www.umn.org.np/umn_signature/email-icon.png] deepak.thapa@umn.org.np<mailto:deepak.thapa@umn.org.np>  |  [http://www.umn.org.np/umn_signature/phone-icon.png]  +977 1 4228118 ext. 110<tel:+977%201%204228118>  |  [http://www.umn.org.np/umn_signature/mobile-icon.png]  +977 9841917554<tel:+977%209841917554>
[http://www.umn.org.np/umn_signature/sign_logo.jpg]<http://www.umn.org.np/>
[http://www.umn.org.np/umn_signature/f.jpg]<https://www.facebook.com/umnnepal>[http://www.umn.org.np/umn_signature/g.jpg]<https://plus.google.com/+UnitedMissiontoNepalKathmandu>[http://www.umn.org.np/umn_signature/t.jpg]<https://twitter.com/umnnepal>[http://www.umn.org.np/umn_signature/l.jpg]<https://www.linkedin.com/company/united-mission-to-nepal>[http://www.umn.org.np/umn_signature/y.jpg]<https://www.youtube.com/umnepal>[http://www.umn.org.np/umn_signature/bottom.jpg]



________________________________

**Comment by sachit-singh** [comment]
Glad to be of help Deepak ji.

**Comment by deepakt3** [comment]
Dear Sachit ji,

Namaste !


We need to change the contact person details in IATI published file. Could you kindly support me to change the contact person's details in IATI published file .

Hope to get support from you as earlier.


With best regards,


Deepak


DEEPAK THAPA
Funds Management Officer  |  Funding Management Team
[http://www.umn.org.np/umn_signature/email-icon.png] deepak.thapa@umn.org.np<mailto:deepak.thapa@umn.org.np>  |  [http://www.umn.org.np/umn_signature/phone-icon.png]  +977 1 4228118 ext. 110<tel:+977%201%204228118>  |  [http://www.umn.org.np/umn_signature/mobile-icon.png]  +977 9841917554<tel:+977%209841917554>
[http://www.umn.org.np/umn_signature/sign_logo.jpg]<http://www.umn.org.np/>
[http://www.umn.org.np/umn_signature/f.jpg]<https://www.facebook.com/umnnepal>[http://www.umn.org.np/umn_signature/g.jpg]<https://plus.google.com/+UnitedMissiontoNepalKathmandu>[http://www.umn.org.np/umn_signature/t.jpg]<https://twitter.com/umnnepal>[http://www.umn.org.np/umn_signature/l.jpg]<https://www.linkedin.com/company/united-mission-to-nepal>[http://www.umn.org.np/umn_signature/y.jpg]<https://www.youtube.com/umnepal>[http://www.umn.org.np/umn_signature/bottom.jpg]



________________________________

**Comment by sachit-singh** [comment]
Dear Deepak Ji,

Namaste ! Do you mean changing the Contact Information for the Activity XI-IATI-1002-SLD ? If so, you would need to go to the activity details page, and on the right hand side menu, you should be able to see a Contact Info label. Clicking on that will take you to the Contact Info form, where you would need to make the necessary changes and click 'Save'. After that the activity would be taken to the 'Draft' stage. Now you would need to publish the activity in order for the changes to be reflected on the IATI Registry.

I hope this helps. Please let me know if you have any other difficulties. Have a good day Deepak Ji.

Best Regards,
Sachit
