### ISSUE TITLE
'other-identifier' field into csv

### ISSUE THREAD

**Issue by DanielHickin** [younginnovations/aidstream#123]
Hi AidStream. I recently had to update our IATI Identifier from the GB-1 to GB-CHC. I am also new to AidStream, and was advised that I would need to update manually the 'other-identifier' field on over 120 individual activities. It would be a great help if this field could be included in the csv. Many thanks in advance for your advice and help. Daniel

**Comment by rupakhetianjana** [comment]
Hello Daniel,

This is an interesting suggestion to include other identifiers into CSV. However, we will let you know if we incorporate this feature in the near future.

Apologies for the long silence through our end.

Thank you.
Anjana
