### ISSUE TITLE
Org File not updating

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#124]
Hi AidStream,

The organisation DCAF registered with AidStream with an incorrect IATI Org ID. This was corrected on AidStream before they published their data to the IATI Registry.

However, their Org File is still showing their wrong IATI Org ID for their reporting org.

Please can this be fixed or let them/me know how to fix this.

Thank you.

Amy

**Comment by sachit-singh** [comment]
Dear Amy,

The Reporting Organisation identifier for DCAF is 'CH-FDJP-109458452' which is the same in the xml file linked to the registry. You can see it [here](https://aidstream.org/files/xml/dcaf-org.xml). Is this what you mean?

Best Regards,
Sachit

**Comment by amy-silcock** [comment]
Thanks Sachit. Yes it is now working.

Prior to this it was appearing as XI-IATI-CH-FDJP-109458452 for me.

Thanks, Amy
