### ISSUE TITLE
Participating Org Error

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#126]
Hi AidStream,

Talking with BEIS who are using AidStream. They have encountered an error when on the 'Organisation' tab and are trying to add a new participating organisation. They type in the name of the organisation (who are not yet publishing to IATI and haven't yet been included elsewhere in their activities) and no 'drop down' list appears for them. This prevents them adding the new organisation.

It works fine on my laptop, but not on theirs?

**Comment by SJ-bond** [comment]
Hi - we also found Amy's issue when we were training people to use AidStream two weeks ago - the people using Microsoft browsers and Opera browsers were not able to add organisations. The feature worked fine on Chrome and Firefox. Also it was not evident that the user has to add new organisations to a separate list found on the dashboard/organisation tab - we kind of worked it out in the workshop together! Please would you improve the help provided on this?

**Comment by PetyaKangalova** [comment]
I have also just been alerting by a publisher (IDLO) that there inconsistencies in the current participating org list - I have copied you in my response to them.

I can see organisations can suggest edits, but wanted to check where you have pulled the original list and why there are differences with the organisation identifiers on the Registry. See screenshots below. Thanks!

![image](https://user-images.githubusercontent.com/24607542/36210404-3b9cf096-1196-11e8-942c-2bc871a43eea.png)


IATI organisation identifiers on the IATI Registry.
![image](https://user-images.githubusercontent.com/24607542/36210267-e385fc4a-1195-11e8-8a61-78ec3a94b373.png)

**Comment by sachit-singh** [comment]
Dear Amy and Sarah,

I am sorry that I could not get back to you sooner. Could you use Chrome or Firefox for now, as there is a compatibility issue with IE. It works on Edge though. We are working on it. I will have you notified once it has been resolved.

Best Regards,
Sachit

**Comment by sachit-singh** [comment]
Dear Petya,

Anjesh will be getting back to you on this matter. Apologies for the late reply.

Best Regards,
Sachit

**Comment by PetyaKangalova** [comment]
@anjesh  Has there been any update on this? It will be good to provide IDLO with an update as soon as possible.

Thanks,
Petya

**Comment by anjesh** [comment]
Hi @PetyaKangalova apologies for getting late on this. US-1 appears to be coming from one of the organisation-xml-file. The identifier is now updated to US-GOV-1.

**Comment by anjesh** [comment]
resolved.
