### ISSUE TITLE
Activity overview: scope presented with wrong text

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#13]
When I look at an activity (http://newstage.aidstream.org/activity/1279) I see under "Activity Scope" that is says "General enquiries [1]". Editing the element shows the correct list "1 - Global". Looks like the wrong table is linked in the overview?
![2016-03-03_02](https://cloud.githubusercontent.com/assets/223935/13497326/0a500384-e155-11e5-818f-3972d67e4147.png)

**Comment by sachit-singh** [comment]
This issue has already been fixed.
