### ISSUE TITLE
Adding Registration Agencies

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#130]
Hi,

Please can the following codes be added:

Superintendencia Nacional de los Registros Públicos (Peru): (PE-SUNARP)
Tanzanian Revenue Authority (TZ-TRA)
Registrar of Companies in Mauritius [MU-CR)
Dubai Multi Commodities Centre' (AE-DMCC)
Department of Associations (Ministry of Interior, Turkey)' (TR-MOI)

(From https://github.com/org-id/register/issues/created_by/amy-silcock)

Thank you,

Amy

**Comment by sachit-singh** [comment]
Done.
