### ISSUE TITLE
Registration Agency CO-RUE

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#132]
Hi AidStream,

Please can the Registration Agency CO-RUE be added
http://org-id.guide/list/CO-RUE 

Many thanks,

Amy

**Comment by amy-silcock** [comment]
Please can we also add:

ES-RMC
http://org-id.guide/list/ES-RMC

And
ES-CIF
(company tax identification code) from the tax office (Delegación de Hacienda)

**Comment by sachit-singh** [comment]
Done.
