### ISSUE TITLE
Publishing extra Org Files

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#134]
Hi AidStream,

An issue is occurring with a few publishers where they are publishing details of their participating orgs in their Org File. To others, it appears that DFID (for example) have multiple Org files when in fact these are being published by organisations they are funding.

e.g: 
![image](https://user-images.githubusercontent.com/27764077/39248225-669e4a68-4893-11e8-8fdd-f32c4e3a0510.png)

Please can it be made harder for organisations to publish org files for their partner organisations as per the screenshot above. Details of partner organisations should be in their activity files. Rarely will organisations need to publish these in their org file (except under the budget broken down by the recipient-organisation).

Many thanks,

Amy

**Comment by anjesh** [comment]
Will be taken care of here https://github.com/younginnovations/aidstream/issues/146
