### ISSUE TITLE
Org file not validating

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#135]
Hi AidStream,

The publisher Comité pour l'abolition des dettes illégitimes (cadtm) can't complete their org file as it says their 'name' is missing.

Can you fix this, as they have added their name and I'm not sure what the error is.

![image](https://user-images.githubusercontent.com/27764077/39361051-9cc6c09e-4a18-11e8-9912-52b6f23bce4d.png)

Best wishes,

Amy

**Comment by kelbayar** [comment]
I've been going crazy with this same issue. Was this ever resolved?

**Comment by amy-silcock** [comment]
Hi @kelbayar,

I've just had a look and you have an org file published on the IATI Registry: https://www.iatiregistry.org/publisher/cadtm

And it's saying published in AidStream: 
![image](https://user-images.githubusercontent.com/27764077/41847602-6be920c4-7872-11e8-9eeb-68d036223fe8.png)

So I'm guessing the answer is yes!

**Comment by kelbayar** [comment]
Hi Amy -- glad that they got it solved, but I am having the same issue with my organization (sorry for not being more clear). See screen shot below. I wonder how the Comite solved their bug? Do you have any ideas? 
![1](https://user-images.githubusercontent.com/29731712/41855269-315da9fa-7860-11e8-8eab-a978a69482f7.jpg)

**Comment by anjesh** [comment]
@kelbayar @amy-silcock these are temporarily fixed for now. We will look into the issue in details.

**Comment by 77karuna** [comment]
This issue has been solved.

Thanks.

Regards,
Karuna
On behalf of AidStream Team
