### ISSUE TITLE
Registration Agency RW-RGB

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#136]
Hi Aidstream,

Please can the Registration Agency RW-RGB be added?
http://org-id.guide/list/RW-RGB

Thank you,
Jahnvi

**Comment by sachit-singh** [comment]
Dear jahnvidave,

The registration agency has been added.

**Comment by jahnvidave** [comment]
Hi Sachit-Singh,

Thank you for adding the registration agency (RW-RGB).

However, it is not appearing on Aidstream in the list for 'Organisation Registration Agency', for Rwanda. 

![image](https://user-images.githubusercontent.com/38503709/39765919-e27e29cc-52da-11e8-8ac3-f0b926b8aacb.png)

This is on Aidstream Lite, but I have also tried on Aidstream Core. Rwanda Governance Board (RGB) is not appearing on either Core or Lite when I attempt to add it as the registration agency for an organisation.

Please can you look into this?

Thank you,
Jahnvi

**Comment by sachit-singh** [comment]
Dear Jahnvi,

It seems the deployed tag hadn't been updated successfully. It has been resolved now. I apologize for the inconvenience and appreciate your understanding.

Sachit

**Comment by jahnvidave** [comment]
Hi Sachit,

Thank you for resolving this. It is now appearing in both Aidstream Lite and Core.

Jahnvi
