### ISSUE TITLE
Contact Information are not imported during CSV Activities Import

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#138]
The following fields are not imported when using the template containing contact information

For example [other_fields_transaction.txt](https://github.com/younginnovations/aidstream/files/2029624/other_fields_transaction.txt) doesn't import the contact info into Aidstream

```
Contact Type
Contact Organization
Contact Department
Contact Person Name
Contact Job Title
Contact Telephone
Contact Email
Contact Website
Contact Mailing Address
```

**Comment by manibibek** [comment]
@anjesh The issue has been fixed and deployed to production

**Comment by anjesh** [comment]
contact information are imported now.
