### ISSUE TITLE
Error during results upload

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#139]
## what

- [ ] fix error during results upload

## why

Few users have reported that when they import results as per template defined in Aidstream, they get the following error

![image](https://user-images.githubusercontent.com/120488/40761678-6743ba58-64bc-11e8-807d-df945fd5c44f.png)

The template looks ok. Here's an
[example csv](https://github.com/younginnovations/aidstream/files/2056621/results.test.1334.hrs.1.txt) that gives error

**Comment by manibibek** [comment]
The file is not in the correct CSV format hence it's not supported

**Comment by anjesh** [comment]
@manibibek could you upload the same file with correct format? Also mention which columns are incorrectly used.

**Comment by manibibek** [comment]
@anjesh i copy pasted whole data from excel to a new excel file and saved the file as csv. It worked. The previous file did not have any comma's in between the rows

**Comment by anjesh** [comment]
I don't understand, i see commas in the above attached file

![image](https://user-images.githubusercontent.com/120488/40911459-85f3bde0-680e-11e8-8c4b-ea75b4640167.png)
