### ISSUE TITLE
List of "dummy participating organization"?

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#14]
When I look at the participating organisations, I see a list with all the same heading, I have to open each one.
![2016-03-03_03](https://cloud.githubusercontent.com/assets/223935/13497452/960dd95a-e155-11e5-9054-5a5ac676ba27.png)

Since I can only edit them all together, would it be possible to instead show a table so that I only have to open it once? A bit like:

| role | id | name |
| --- | --- | --- |
| Funding | NL-1 | Ministerie van Buitenlandse Zaken |
| Implementing | NL-KVK-34214586 | Partos |
| ... | ... | ...etc... |

**Comment by rolfkleef** [comment]
The same applies to Results: you need to click to open a few levels before you can see a title

**Comment by sachit-singh** [comment]
The list of dummy texts have been replaced with relative texts.

**Comment by MettePfeiffer** [comment]
Still not closed when it comes to the Results: You just see 'Outcome [2]', and have to click twice for each Outcome to see the Title. Would it be possible to include the Title in the overview as well?

![image](https://cloud.githubusercontent.com/assets/18529686/14602162/c2caa0ce-0566-11e6-8c7d-f5fc8e5edc5f.png)
