### ISSUE TITLE
CSV uploads with curly quotes gives errors

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#140]
## What

- [x] convert curly quotes to straight quotes for both single and double quotes in all the activities csv upload
- [x] convert curly quotes to straight quotes for both single and double quotes in all the transactions csv upload
- [x] convert curly quotes to straight quotes for both single and double quotes in all the results csv upload

## Why

When the CSV file contains curly quotes, the csv upload gives error. For example [data-issues.csv](https://github.com/younginnovations/aidstream/files/2060926/data-issues.txt) contains curly braces 
![image](https://user-images.githubusercontent.com/120488/40820190-ca65df18-657e-11e8-8134-7b6defd82bd6.png). Note curly quotes. 

If you upload that file, you would get the error saying

```
· Activity Identifier is required.
· Title is required.
· description is required
```

When you change that curly brace to straight brace, it works. Note straight quotes below. 

![image](https://user-images.githubusercontent.com/120488/40820501-a224ddc2-6580-11e8-928b-678de143cd1f.png)

cc @sachit-singh

**Comment by manibibek** [comment]
For now, i have encoded the content of the csv file to UTF-8 standard which shows the curly quotes as "?" as shown in the screenshot. This allows the file to be imported correctly for now
<img width="1218" alt="screen shot 2018-06-07 at 10 57 36 am" src="https://user-images.githubusercontent.com/18477559/41079590-1b53099c-6a42-11e8-9bc5-c3c35cb4adbf.png">

**Comment by anjesh** [comment]
This works for now. Great. Users will fix in the data in case of such characters.
