### ISSUE TITLE
Registration Agencies: IT-CF and IT-RI

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#142]
Hi Aidstream,

Please can these 2 Registration Agencies in Italy be added to Aidstream?

IT-CF
http://org-id.guide/list/IT-CF

IT-RI
http://org-id.guide/list/IT-RI

Thank you,
Jahnvi

**Comment by manibibek** [comment]
The Agencies IT-CF and IT-RI has been added. 
Thank you

**Comment by jahnvidave** [comment]
Thank you!
