### ISSUE TITLE
Disable publishing of partners organisations information.

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#146]
What 
====

- [x] publishing workflow for the partners organisation is hidden and disabled (hence it shouldn't show the workflow state like draft, completed as can be seen below)
- [x] partner organisation is not clickable and data is not possible to enter (currently you can click the organisation and see the details and add further information)

![image](https://user-images.githubusercontent.com/120488/41518794-0859bf7a-72e4-11e8-8564-d93f16b36b2a.png)

We need to see how many organisations have published the partner organisations' data and need to decide what to go about it. 

Why
====

See here https://github.com/younginnovations/aidstream/issues/134

cc @sachit-singh

**Comment by manibibek** [comment]
@anjesh the changes has been pushed to production
