### ISSUE TITLE
Document-link issue for Farm Africa

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#148]
- [x] fix document-link issue for Farm Africa

---
Notes:

Clicking document-link for Farm Africa gives the following screen

![image](https://user-images.githubusercontent.com/120488/42211673-db7b1408-7ed3-11e8-8ef7-c79128a0c14d.png)

The log shows the following error 

`
Next ErrorException: htmlentities() expects parameter 1 to be string, array given (View: /resources/views/Activity/documentLink/index.blade.php) in ..vendor/laravel/framework/src/Illuminate/Support/helpers.php:466
`

**Comment by manibibek** [comment]
@anjesh this issue has been fixed, there was slight format error in the saved json data
