### ISSUE TITLE
Uploaded CSV text auto lowercased after import

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#149]
- [x] text (other than lang) should be as per in the file in all the csv import module (results, transactions)

## Notes

---

When the followings results csv is imported into the system, 

![image](https://user-images.githubusercontent.com/120488/42214968-ca1d5f6e-7edc-11e8-8a80-02d4269ce07e.png)

it is shown in upper case in the import screen. 
![image](https://user-images.githubusercontent.com/120488/42213835-99275d36-7ed9-11e8-96da-0cb66e4fb361.png)

After import, all the data are lower-cased

![image](https://user-images.githubusercontent.com/120488/42213863-ac9763fc-7ed9-11e8-9ebb-51725f5b5377.png)

This bug might have been introduced when fixing this issue https://github.com/younginnovations/aidstream/issues/145

**Comment by manibibek** [comment]
@anjesh this issue is fixed now
