### ISSUE TITLE
Transaction Failing Validation For Non Mandatory Fields

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#15]
I amended a transaction for my demo organisation activity 'N545-FY2013' at v2.02 and changed the transaction type from Incoming Funds to Incoming Commitment and tried to save. The validation was requiring that I also provide the following fields: Disbursement channel code, sector & region code. However none of these fields are mandatory for a transaction?

**Comment by sachit-singh** [comment]
The validation for the non mandatory fields have been fixed.
