### ISSUE TITLE
UX change in Participating-organisation interface

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#152]
- [x] update the UX of Participating-org interface as shown below. The user has to select the checkbox saying "I have org registration number of this organisation", then only there will be option to select the "list of organisation" and input box to enter the org-identifier.

## Why

Currently the user has to select one of the list before being able to add the organisation, she mightn't have any clue about the identifier and yet she will have to select one random item from the list to move forward.

![image](https://user-images.githubusercontent.com/120488/42566555-b1b39d4e-8526-11e8-8c0a-65876877dab3.png)

The proposed solution is to have the following UI 

```
ORGANISATION TYPE
COUNTRY THE ORGANIZATION IS BASED IN
ORGANISATION NAME
[ ] I have organisation registration number for above organisation.
Submit
```

If checked, then she will be presented with the following
```
ORGANISATION TYPE
COUNTRY THE ORGANIZATION IS BASED IN
ORGANISATION NAME
[x] I have organisation registration number for above organisation.
PLEASE CHOOSE A LIST FROM BELOW:
ORGANISATION REGISTRATION NUMBER
Submit
```

cc @manibibek

**Comment by manibibek** [comment]
@anjesh the changes has been deployed
