### ISSUE TITLE
Registration Agency: CR-RPJ

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#154]
Hi Aidstream,

Please can the Registration Agency CR-RPJ be added to Aidstream?

This is for the Registro de Personas Jurídicas (Costa Rica). As discussed here: https://github.com/org-id/register/issues/235.

Thanks,
Jahnvi

**Comment by manibibek** [comment]
@jahnvidave Registration Agency CR-RPJ has been added
