### ISSUE TITLE
Registration Agency: IL-RA

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#159]
Hi Aidstream,

Please can the Registration Agency IL-RA be added to Aidstream?

This is for the Rasham Ha'amutot . As discussed here:https://github.com/org-id/register/issues/237#issuecomment-405844584 and will be shortly added to Org ID.

Thanks,

Amy

**Comment by amy-silcock** [comment]
Hi all, any chance this could be added today?

**Comment by manibibek** [comment]
Registration Agency IL-RA has been added

Thank you

**Comment by amy-silcock** [comment]
Thank you
