### ISSUE TITLE
Registration Agency: JO-MSD

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#160]
Hi Aidstream,

Please can the Registration Agency JO-MSD be added to Aidstream?

This is for the Register of Associations, Jordan - http://org-id.guide/list/JO-MSD.

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Registration Agency JO-MSD has been added. 

Thank you

**Comment by jahnvidave** [comment]
That is great. Thank you!
