### ISSUE TITLE
Registration Agency: TZ-NNCB

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#161]
Hi Aidstream,

Please can the Registration Agency TZ-NNCB be added to Aidstream?

This is for the Tanzania National NGO Coordination Board - http://org-id.guide/list/TZ-NNCB.

Thank you,
Jahnvi

**Comment by manibibek** [comment]
The Registration Agency TZ-NNCB has been added. 

Thank you

**Comment by jahnvidave** [comment]
Thank you!
