### ISSUE TITLE
Error during "mark as complete" action

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#164]
- [x] fix error in "Mark as Complete" action

When you click https://aidstream.org/activity/18843 for "International Rescue Committee Inc.", it gives "Something went wrong." with the log "Exception: String could not be parsed as XML".

**Comment by manibibek** [comment]
@anjesh on checking, i found an invalid character in one of the transaction shown below. 
<narrative>\u10 International Rescue Committee Inc.</narrative>

For Now I have removed that character and the status is changing successfully.
