### ISSUE TITLE
Unknown error importing XML file

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#166]
- [x] issues with the following XML is identified
- [x] proper error reporting if the XML is not correct 

The following XML doesn't get imported in the system when trying to upload. It doesn't give any error except that there's problem with XML and the message disappear. 

[IATIFile_Bangladesh.txt](https://github.com/younginnovations/aidstream/files/2296568/IATIFile_Bangladesh.txt)

**Comment by manibibek** [comment]
The import was successful when we removed the "<ir:registry.." tag in line number 3 from the above file. 
For now, the file can be imported by removing that tag. 

We are also working on how we can show proper information for such kind of errors.

**Comment by manibibek** [comment]
The XML import issue has been fixed in https://github.com/younginnovations/aidstream/commit/1917421e8afc931133caeb9e37e098620d6f1b10

**Comment by anjesh** [comment]
Great. Error is showing for such XML with non-standard elements.

![image](https://user-images.githubusercontent.com/120488/44522826-85fec780-a6f7-11e8-8f4a-987bf84f1420.png)
