### ISSUE TITLE
Issue with participating organisation addition.

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#167]
- [x] the issue with PO addition is identified
- [x] the user is able to click "User this organisation" button

### Note

Few users have reported that they can't move forward in "participating organisation". They complained that they can't click "Use this organisation button". 

![image](https://user-images.githubusercontent.com/120488/44257129-cf986f80-a22a-11e8-84bb-48eb84352b73.png)

Some users have even faced this issue in Chrome. We are looking into this issue and will fix it as soon as we are able to identify the cause. 

Those of you who have come across this issue, please write in the comment below - Browser name and version e.g.( google chrome Version 68.0.3440.106), and Operating system e.g. (windows10, Ubuntu 18, mac high sierra)

**Comment by anjesh** [comment]
It appears that the issue is with add-new-organisation page from organisation-list page.

![image](https://user-images.githubusercontent.com/120488/44400705-e52fd100-a56b-11e8-9f30-9caf4ada5759.png)

![image](https://user-images.githubusercontent.com/120488/44400744-04c6f980-a56c-11e8-82b7-1f6487efb8be.png)

we get the following js error
```
spread.js:25 Refused to set unsafe header "Origin"
(anonymous) @ spread.js:25
create:491 Uncaught ReferenceError: publisher is not defined
    at VueComponent.selected (create:491)
    at click (eval at createFunction (vue.js:10667), <anonymous>:3:9295)
    at invoker (vue.js:2029)
    at HTMLAnchorElement.fn._withTask.fn._withTask (vue.js:1828)
```

**Comment by manibibek** [comment]
@anjesh The issue has been fixed

**Comment by anjesh** [comment]
Also i just found that i can't click on the org if found in the list @bhojport 

![image](https://user-images.githubusercontent.com/120488/44641559-2a7a5580-a9e7-11e8-9a18-21cf051d58ee.png)
