### ISSUE TITLE
Upload activities: use DAC-5 instead of DAC-3?

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#17]
The upload template currently has DAC3 as a required column. Would it be possible to add DAC5 as well? Or use that instead.

A related question: how to add multiple values (sectors, participating orgs, countries)

**Comment by sachit-singh** [comment]
To add multiple values, one is to separate the filled values using a semicolon ";".

DAC-5 has been used instead of DAC-3 as well.
