### ISSUE TITLE
Registration Agency: PK-SEC

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#175]
Hi Aidstream,

Please can the Registration Agency PK-SEC be added to Aidstream?

This is for the Securities and Exchange Commission of Pakistan - http://org-id.guide/list/PK-SEC.

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvidave, 

The Registration Agency has been added to Aidstream. 

Thank you
