### ISSUE TITLE
Registration Agency: LK-DRC and LK-NGO

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#177]
Hi Aidstream,

Please can these two registration agencies be added to Aidstream?
- LK-DRC 
for Department of the Registrar of Companies (Sri Lanka) - https://github.com/org-id/register/pull/274
- LK-NGO 
for Sri Lanka - National Secretariat for Non-Governmental Organisations - https://github.com/org-id/register/pull/272

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi, 

The Registration Agencies LK-DRC and LK-NGO has been added to Aidstream. 

Thank you

**Comment by jahnvidave** [comment]
Thank you!
