### ISSUE TITLE
Result element related issues

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#178]
- [x] `result > indicator > baseline > year` attribute must be **required** as per IATI Standard
  - Currently year attribute is required only on input of value attribute 
- [x] `result > indicator > baseline > value` attribute must be **required** as per IATI Standard
  - Currently year attribute is required only on input of date attribute 
- [x] `result > indicator > period > period-start` attribute must be **required** as per IATI Standard
- [x] `result > indicator > period > period-end` attribute must be **required** as per IATI Standard
  - Currently, period-start attribute is required only on input of period-end attribute or vice-versa.
- [x] `result > indicator > period > period-start` must be **before or the same** as p`result > indicator > period > period-end` attribute
  - Currently same dates for period-start and period-end is not possible.
- [x] `result > indicator > reference > vocabulary` attribute must be **required** as per IATI Standard
- [x] `result > indicator > reference > code` attribute must be **required** as per IATI Standard
- [x] `result > indicator > reference > indicator-uri` attribute must be **required** as per IATI Standard, _only when_ `result > indicator > reference > vocabulary`  is **99** and must be **uri**
- [x] `result > indicator > reference` Multiple vocabularies may be specified, but each vocabulary may be specified only once for each indicator.
- [x] `result > indicator > period > target > value` and `result > indicator > period > actual > value` attribute smust be **required** as per IATI Standard
  - Currently: The Value field is required **only when** Location Reference, Name, Value, Narrative, Language are present.

**Comment by manibibek** [comment]
This issue has been fixed
