### ISSUE TITLE
Transaction element related issues

### ISSUE THREAD

**Issue by 77karuna** [younginnovations/aidstream#179]
- [x] `transaction > transaction-date` attribute **must not** be in the future.
- [x] `transaction > value > value-date` attribute **must not** be in the future.
- [x] `transaction > value` attribute 
  - How many decimal points to be allowed for entry?
  - How many decimal points to be shown in list?
 - [x] `transaction > sector` 
Multiple sector can't be deleted.

**Comment by rupakhetianjana** [comment]
- [x] `transaction`
Inside the transaction element, the filter should be added in transaction type and transaction date.

**Comment by manibibek** [comment]
The issue has been fixed in https://github.com/younginnovations/aidstream/commit/1fbe725e5b0907b28c994b90d42dbd0d3c8f5bb9
