### ISSUE TITLE
Change 'Who're' to 'Who Is Using' On Main Aidstream Web Page

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#18]
On the Aidstream landing page there is a link in the top RH corner of 'Who're' which I think should be 'Who Is Using'. Also if you click on this link and go to the who is using page the logo for ADD International is displayed multiple times

**Comment by imlunek** [comment]
- `Who're using` has been changed to `Who's using`.
- On `Who's using` page, organizations are now listed dynamically.
