### ISSUE TITLE
Planned Disbursement element related issues

### ISSUE THREAD

**Issue by 77karuna** [younginnovations/aidstream#180]
- [x] `planned-disbursement > value` attribute should display actual values in decimal point in preview.
  - Currently, decimal points are rounded up.
- [x] `planned-disbursement > provider-org > ref` 
`planned-disbursement > receiver-org > ref` 
- [x] `planned-disbursement > provider-org > type` 
`planned-disbursement > receiver-org > type` 
value **must** be on the OrganisationType codelist
  - Need to display dropdown with OrganisationType codelist in place of only input element.

**Comment by manibibek** [comment]
The issue has been fixed on https://github.com/younginnovations/aidstream/commit/887b26adbece021b3c479ddc1c7fa68b6ac79ed5
