### ISSUE TITLE
Aid-type related issues

### ISSUE THREAD

**Issue by 77karuna** [younginnovations/aidstream#186]
- [x] `aid-type > vocabulary` element 
_Each selected vocabulary should only be used once for each activity_
Currently, multiple entry of same vocabulary is possible. 

- [x] `aid-type > vocabulary` + `aid-type > code` element 
_The @code attribute declares a valid code from the specified codelist._
Vocabulary

1. 1 OECD/DAC -> Common aid typology 
   - Code: A01 , A02 , ...
     - Ref: http://reference.iatistandard.org/203/codelists/AidType/
2. 2 Earmarking Category -> High level earmarking
   - Code: 1 , 2, 3, 4
     - Ref: http://reference.iatistandard.org/202/codelists/EarmarkingCategory/
3. 3 Earmarking Modality -> Detailed level earmarking
   - Code: A , B, C, D
     - Ref: Page 16 (Annex	I. Earmarking modalities)
     https://reliefweb.int/sites/reliefweb.int/files/resources/Grand_Bargain_final_22_May_FINAL-2.pdf 

All of the above applicable for elements:
 - `default-aid-type` 
 - `transaction > aid-type`

**Comment by manibibek** [comment]
This issue has been fixed
