### ISSUE TITLE
V2.03 Miscellaneous Elements Issues

### ISSUE THREAD

**Issue by 77karuna** [younginnovations/aidstream#188]
- [x] `Participating-org > crs-channel-code`
  Add channel codes in front of channel code names.
  e.g. 10000 | PUBLIC SECTOR INSTITUTIONS 
- [x] `Transaction > transaction-type`
  Update Transaction type codes as follows:
  1. _2 - Commitment_ ==> **2 - Outgoing Commitment**
  2. _5 - Interest Repayment_ ==> **5 - Interest Payment**
- [x] `Tag > narrative`
  Narratives are not required elements.
- [x] `Document-link > description`
  The _optional_ description element of a @document-link element was added.
  Currently, this is required.
- [x] `Recipient-region > vocabulary-uri`
  If a publisher uses a vocabulary of 99 (i.e. ‘Reporting Organisation’), then the @vocabulary-uri attribute should also be used.
  Currently, this is optional even if 99 vocabulary is used.

**Comment by manibibek** [comment]
The Issues has been fixed
