### ISSUE TITLE
Post Ugrade To V2.02 Only Limited Activity Elements Available

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#19]
I have just upgraded my 'demo' account to v2.02 and ticked to include fields such as humanitarian and results in 'Settings' but when editing an activity i only appear to be able to edit either the data that already exists in my migrated activity or just the following as listed under 'Basic Activity Information' in the RH sidebar - title, description, status, date, contact info, scope. Where can I get access to edited or add other elements. I am using Chrome as my browser?

![image](https://cloud.githubusercontent.com/assets/5500787/14013047/e2a38f06-f1a1-11e5-8016-3b290bb26a82.png)

**Comment by sachit-singh** [comment]
There is a different scroll bar for the right hand side element menu. Please try hovering on the element menu and scrolling down. You would then be able to see other activity elements.

**Comment by wendyrogers** [comment]
Brilliant. Thanks I can see it now but as you say I did have to hover to make it visible? is there any way that you can make it more obvious at all and perhaps not hidden until you hover over it?

**Comment by sachit-singh** [comment]
Yes. There has been some design changes regard the interface and we have already started working on it. We will let you know as soon as the interface has been changed. Thank you.
