### ISSUE TITLE
Registration Agency: IQ-NGO

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#190]
Hi Aidstream,

Please can the Registration Agency IQ-NGO be added to Aidstream?

This is for the NGO Directorate (Republic of Iraq) - http://org-id.guide/list/IQ-NGO.

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvidave, 

The Registration agency has been added to Aidstream. 

Thank you
