### ISSUE TITLE
Registration Agency: NE-DGI

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#192]
Hi Aidstream,

Please can the Registration Agency NE-DGI be added to Aidstream?

This is for the Tax Directorate (Niger) - https://github.com/org-id/register/pull/291 

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvidave, 

The Registration Agency NE-DGI has been added to Aidstream. 

Thank you
