### ISSUE TITLE
Changing 'Publisher ID' for IFDC

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#193]
Hi AidStream,

Following conversations with the IATI technical team, [IFDC](https://iatiregistry.org/publisher/ifdc-us) have changed their Publisher ID on the IATI Registry, (to better reflect their organisation as a whole, rather than a particular project).

We have tried changing their Publisher ID in the Publishing Settings of their AidStream account. However, this has been unsuccessful.

We receive the following message: 'Your publisher id is being changed. In the meantime, you cannot change your registry settings. Thank you for your patience.' 

However, the Publisher ID has not changed. This is preventing IFDC from publishing their data.

![ifdc publisher id aidstream](https://user-images.githubusercontent.com/38503709/48129446-6b150b80-e281-11e8-8f8b-48bf9794a35f.png)

Please can you have a look at why this change is not being reflected in their AidStream settings and look into resolving this.

Thank you, Jahnvi

**Comment by 77karuna** [comment]
Hello Jahnvi,

The Publisher ID of [IFDC](https://iatiregistry.org/publisher/ifdc-us) has been changed successfully in their AidStream account.

![ifdc_publisherid_changed](https://user-images.githubusercontent.com/43775456/51372883-c0458700-1b26-11e9-9494-0c5a6cc50ab0.png)

Please confirm this from your end as well.

Thank you
Karuna

**Comment by jahnvidave** [comment]
Hi Karuna,

Thank you for your reply. Yes, having checked their account, I can see that their Publisher ID has updated successfully.

Many thanks,
Jahnvi
