### ISSUE TITLE
Registration Agency: SE-ON

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#195]
Hi Mani Bibek,

It was great to meet you and the YoungInnovations team at the TAG last week!

Please can the Registration Agency SE-ON be added to Aidstream?

This is for the Business Registration Number, Sweden - http://org-id.guide/list/SE-ON

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi Dave, 

It was indeed a great moment meeting you and the IATI Team at TAG. 

The Registration Agency SE-ON has been added to Aidstream. 

Thank you

**Comment by jahnvidave** [comment]
Thank you!
