### ISSUE TITLE
file deleted

### ISSUE THREAD

**Issue by jacqkodden** [younginnovations/aidstream#196]
I was entering information in aidstream and by accident I deleted a whole file from an organisation we do business with. Is it possible to restore the file? There's data in this file from years. File name is Down to Zero Programme DCI-ECPAT NL - Thailand.

Like to hear from you.

Kind regards
Sabina

**Comment by rupakhetianjana** [comment]
Hello Sabina,

It is impossible to restore the deleted file. But if you have published that file in IATI, you can download the XML file from there and can upload in AidStream. After that, you can overwrite manually for the necessary changes.

Regards,
Anjana
