### ISSUE TITLE
Set Language Field For Narrative & Text Fields To Language Default

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#20]
For narrative and text fields there is generally also an associated language field. Could the initial associated language fields always be set to the specified default language value so that the user only needs to change this value for exceptions or additional instances of the element ?

**Comment by anjesh** [comment]
My understanding is you don't need to mention the default language when the language of the narrative is default lang. If default lang is to be selected, then we can go with your solution.

**Comment by wendyrogers** [comment]
You are quite correct @anjesh that the language attribute is not mandatory with the narrative field if the default has been specified. However, I would anticipate that many Aidstream users who are not so IATI savvy will see the language fields with the instruction 'Select from the drop down list' and will think that they will need to select a value each time. Therefore it would be good if we could save them time here perhaps by setting those fields to the default values (even if it is technically not required)

@sarah @fiona - any thoughts on this?

**Comment by SJ-bond** [comment]
Hello - yes, if the field can show the default language selected that would be very useful indeed. Similarly with default currency in the transaction fields.

**Comment by sachit-singh** [comment]
This issue was discussed as 'not to be implemented now', so I am closing this.
