### ISSUE TITLE
2.03 Minor issue

### ISSUE THREAD

**Issue by rupakhetianjana** [younginnovations/aidstream#210]
- [x] Transactions (type): type "2" is still indicated as "commitment", 
but Aidstream should be using "outgoing commitment" such as on the 
2.03 codelist
- [x] Result (document-link to results indicator): it's an optional 
attribute for IATI, but for the moment it's mandatory in Aidstream 
(with an asterisk " * " ) ==>we have to make this optional
- [x] The CSV headline of result template should have one heading, while it has two heading currently in all versions.

- [x] V2.03 Miscellaneous Elements Issues https://github.com/younginnovations/aidstream/issues/188

**Comment by manibibek** [comment]
The issues has been fixed
