### ISSUE TITLE
2.03 upgrade bug?

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#214]
Hi guys,

Your 2.03 AidStream is looking good! Great to have this released.

I'm trialing it on my test account and can't save existing activities due to an error with the Default Aid Type. I can't work out why this error is occurring.

My test account is:
![image](https://user-images.githubusercontent.com/27764077/50596995-cb00ea80-0e9d-11e9-8954-c27b7607c4cc.png)

Could you please take a look your end? Or let me know where I've gone wrong.

Many thanks, Amy

**Comment by manibibek** [comment]
Hi Amy, 

On checking, I found that the issue occurred only for Activities which was Imported from XML file in version 2.02 and then the system was upgraded to 2.03. 

We have fixed the issue and now you can save the Activity.

Thank you for letting us know about the issue.
