### ISSUE TITLE
Secondary Email Related Issue

### ISSUE THREAD

**Issue by rupakhetianjana** [younginnovations/aidstream#215]
- [x] Organization name in the support email related to `secondary email` changes/update require one's organization name. (Email being generated from support is taking 1st name of partner organization from the list instead of one's organization if update/change is done in the secondary email.)
- [x] Make secondary email optional.

**Comment by manibibek** [comment]
This issue has been fixed in https://github.com/younginnovations/aidstream/commit/84a9fc35aa06b0f1fa32befde2b2a6d15874bd46
