### ISSUE TITLE
2.03 - something went wrong?

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#217]
Hi,

Friends of the Earth are getting an error message when trying to update their data. It's the 'something went wrong message'. They're trying to move 1.03 data to 2.03.

![image](https://user-images.githubusercontent.com/27764077/50845789-a0afa100-1365-11e9-88b2-0da8629eb0c2.png)

Please can you look into this asap.

**Comment by manibibek** [comment]
Hi Amy,

There was some issue with the data while upgrading which I have fixed now. Now they can update their data. 

Thank You
