### ISSUE TITLE
Updating Activity Status Codelist

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#218]
Hi AidStream,

After discussions on [IATI Discuss](https://discuss.iatistandard.org/t/implemented-as-bug-fix-activitystatus-codes-mixup-of-descriptions-for-codes-3-4/304/65), it was decided that the Activity Status Codelist should be changed to reflect what is actually meant by these terms. These changes were implemented on 6/12/2018.

![image](https://user-images.githubusercontent.com/38503709/50984069-ce791f00-14f8-11e9-8f66-92619dce5675.png)

AidStream is currently showing the old codelist:

![image](https://user-images.githubusercontent.com/38503709/50984033-bacdb880-14f8-11e9-9faa-e567e567a44a.png)

Please can the changes be added to AidStream, so that it is clear to users which code they should be selecting?

Many thanks,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi, 

Thank you for pointing that out. We have updated the Activity Status Codelist. 

Thank you

**Comment by jahnvidave** [comment]
That's great, thank you Mani Bibek!
