### ISSUE TITLE
2.03 - Unable to save changes to 'Settings'

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#220]
Hello,

On the 2.03 upgrade, it is not possible to save changes made to details under 'Settings'. An error occurs when clicking 'Save organisation information':

![image](https://user-images.githubusercontent.com/38503709/51119001-9f6cf100-1809-11e9-954a-3ff2346a9d3a.png)

Please can you have a look into this?

Thanks,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi, 

The issue has been fixed. 

Thank You

**Comment by jahnvidave** [comment]
Thank you @manibibek
