### ISSUE TITLE
INPUD transactions error

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#226]
Hello AidStream,

International Network of People who Use Drugs (INPUD) are not able to publish their activity data as they receive error messages relating to their transaction data.

They receive the message that 'The required Transaction-date is missing from the 'Transaction-date' element of Transaction element.' And that 'The required Value is missing from the 'Value' element of Transaction element.' However, these fields are all completed in their transaction details, and they are unable to remove the error by re-entering the data.

This is affecting multiple activities.

![image](https://user-images.githubusercontent.com/38503709/51916565-7b96d700-23d5-11e9-94c8-ade0abc9969f.png)

Please can you have a look at what is causing this error?

Many thanks,
Jahnvi

**Comment by 77karuna** [comment]
Hi Jahnvi,

After having gone through the issue, we came to the conclusion that, although date related data are complete, the **date format** is incorrect.

The required format is **yyyy-mm-dd**. However, their date is in _yyyy/mm/dd_ format.
![aidstream-inpud-date-format-issue](https://user-images.githubusercontent.com/43775456/51965358-65e6e780-2491-11e9-9d60-01234b3b0e57.png)

This issue will be solved after the transaction dates are entered in correct format.

Thanks,
Karuna

**Comment by jahnvidave** [comment]
Thank you Karuna! I have passed that on to INPUD, so hopefully the errors will be resolved soon.

Many thanks, 
Jahnvi

**Comment by jahnvidave** [comment]
Hi Karuna,

INPUD have raised a valid point, that it is not possible to enter dates in the wrong format, as AidStream automatically formats dates when selected.

Please can you investigate this further, as it is not clear why this error message is appearing and how to resolve it.

Many thanks,
Jahnvi

**Comment by rupakhetianjana** [comment]
Hello Jahnvi,

To resolve this issue, the user has to edit all the transactions one by one, re-select the date, and save the data. 
 
Thank you.
Anjana

**Comment by jahnvidave** [comment]
Hi Anjana,

Thank you for this suggestion - I have passed this on to INPUD, although I think they did already try this, without success. 

Please could you give some further explanation as to why/how this error has occurred?
On the transaction page on AidStream, the dates all appear to be in the correct format, so it is not clear why they are incorrect in the xml?

e.g. this value-date appears in the list of errors, but appears to be fine when editing the transaction:
![image](https://user-images.githubusercontent.com/38503709/53489193-76867f80-3a88-11e9-8037-246ca5a3d9fe.png)

Many thanks,
Jahnvi
