### ISSUE TITLE
Mandatory results fields

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#227]
Hi AidStream,

There are a couple of fields in the Results element that have been set as mandatory fields on AidStream, which are not always required by the IATI Standard.

This is preventing some publishers from updating their data, as they are not able to save their data without filling in these fields.

The fields are:

Indicator Reference
![image](https://user-images.githubusercontent.com/38503709/51975671-bacb3380-247a-11e9-9307-43cb432d9b74.png)

Baseline Year and Value
![image](https://user-images.githubusercontent.com/38503709/51975224-9ae74000-2479-11e9-99cb-7cd78e79260e.png)

Please can you have a look into this?

Many thanks,
Jahnvi

**Comment by 77karuna** [comment]
Hello Jahnvi,

Thank you for pointing out those issues to us. Those listed out have been managed in AidStream.

We have slight confusion regarding, **Baseline > year** attribute in following scenario:
If user enters any baseline attribute such as _value_,  we allow user to save as it is? Do we need to make user mandatory to fill up _year_ attribute or not?
It will be of great help if this confusion could be cleared up as soon as possible.
Thanks in advance.

Kind Regards,
Karuna

**Comment by jahnvidave** [comment]
Hi Karuna,

Thank you for working on these issues.

Regarding the **Baseline > year** attribute:
If a user enters _any_ baseline attribute (such as value), the **year** attribute is then mandatory and users must fill it in.

Do let me know if any other clarifications are needed.

Best wishes,
Jahnvi

**Comment by 77karuna** [comment]
Hello Jahnvi,

> Regarding the **Baseline > year** attribute:
If a user enters _any_ baseline attribute (such as value), the **year** attribute is then mandatory and users must fill it in.

Thank you for clearing this confusion. We will be working on this issue with top priority.

Kind Regards,
Karuna

**Comment by rupakhetianjana** [comment]
Hello Jahnvi,

We have made the changes in `Result` element as per the IATI standards. 
Now *Indicator Reference* and *Baseline attributes* are made optional. But with the requirement of IATI standards such as **@value of `Baseline`, `Target`, & `Actual` must be included for non-qualitative measures**,  fields will get changed.

Thank you!

**Comment by jahnvidave** [comment]
Thank you so much for fixing this Anjana! This is looking perfect.

Many thanks, Jahnvi
