### ISSUE TITLE
2.03 - Unable to import Transaction CSV

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#229]
Hello AidStream,

On the version 2.03 upgrade, the CSV import function is not working for Transactions.

When trying to upload the transactions CSV file, the message appears: 'CSV File Processing', but nothing further happens.
![image](https://user-images.githubusercontent.com/38503709/51982011-bd368900-248c-11e9-99e8-fe059e6512dd.png)

The CSV file itself is correct, and can be uploaded successfully on version 2.02.

Please can you have a look into this?

Many thanks,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi, 

The issue has been fixed. 

Thank you

**Comment by jahnvidave** [comment]
Thank you Mani Bibek
