### ISSUE TITLE
Difficult To Edit Document Link Information When Many Documents Already Added

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#23]
It is very difficult to edit document links when there are already multiple document links present on an activity as finding the document requiring amendment can be quite confusing. Would it not be easier to list the document links on the main activity screen and then allow the user to select the specific document to edit from the list (or add new)?

**Comment by anjesh** [comment]
Yes, in that case, we need to have this something like transactions with the listing first and then add/edit. Will see if this could be released on the first launch or in later sprints.

**Comment by pradhanrak** [comment]
This enhancement has been completed. Now the document links are listed like transactions and results. Users will be able to add and edit document links individually.
