### ISSUE TITLE
Publishers missing from Participating Organisation list

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#231]
Hi AidStream,

There are several publishers that are not appearing on the 'Participating Organisation' drop-down list. 

This is resulting in users adding them in manually using the 'Use Organisation Finder' form, which often leads to errors in the information entered, and means the organisations are not correctly linked.

Please can you have a look at updating the list on AidStream, so that all publishers appear or are searchable on the list of participating organisations?

Many thanks,
Jahnvi

**Comment by rupakhetianjana** [comment]
Hello Jahnvi,

The publishers from the IATI has been updated in AidStream.

Thank you.

Regards,
Anjana
