### ISSUE TITLE
Registration Agency: ES-MDJ

### ISSUE THREAD

**Issue by jahnvidave** [younginnovations/aidstream#232]
Hi AidStream,

Please can the Registration Agency ES-MDJ be added to Aidstream?

This is for the Ministry of Justice, Spain - http://org-id.guide/list/ES-MDJ

Thank you,
Jahnvi

**Comment by manibibek** [comment]
Hi Jahnvi, 

The registration Agency ES-MDJ has been added to Aidstream. 

Thank you

**Comment by jahnvidave** [comment]
Thank you!
