### ISSUE TITLE
Small bug with other identifier codelist

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#235]
When using the other-identifier element. The wrong name for the code B1 is pulling through to the activity overview screen: 

![image](https://user-images.githubusercontent.com/27764077/53486678-4be4f880-3a81-11e9-9062-a39221579383.png)

B1 is: Previous reporting organisation identifier
And not: Reporting Organisation's Internal Activity Identifier

**Comment by manibibek** [comment]
Hi Amy, 

This issue has been solved. 

Thank you

**Comment by amy-silcock** [comment]
Thanks @manibibek. It looks correct.
