### ISSUE TITLE
Registration Agency: AR-CENOC

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#236]
Hi AidStream team,

Please can the following Registration Agency be added to Aidstream. This agency was added by Org ID some time ago but I cannot see that it has been requested to be added to AidStream as well.

Please see Discuss forum post: https://discuss.iatistandard.org/t/added-proposed-addition-to-the-organisation-registration-agency-codelist-argentina/944

And Org ID page: http://org-id.guide/list/AR-CENOC

Code: AR-CENOC
Name: The National Centre of Community Organisations 
Country: Argentina
Description: Law Nº 25.855, de Voluntariado Social (Social Volunteering) established in 2004 a role for El Centro Nacional de Organizaciones de la Comunidad to maintain a database of civil society organisations (CSOs).

Thank you

**Comment by JoshStanleyDevInit** [comment]
Hi team,

It has also come to my attention that the following Identifier is also unavailable on AidStream. Perhaps this can be added at the same time as the above?

Org ID page: http://org-id.guide/list/JE-FSC

Code: JE-FSC
Name: Jersey Financial Services Commission
Country: Jersey
Description: Companies and Non Profit Organisations operating in Jersey register with the Financial Services Commission (JFSC).

**Comment by rupakhetianjana** [comment]
Hi Josh,

Code: JE-FSC & Code: AR-CENOC both have been added to AidStream.

Thank you.

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
Hi Anjana,

Great, thanks for adding them. Can you advise when these will become available on the system? I can't currently see them when I select AR or JE on the Country field.

Thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

Can you please check again.

Looking forward to your response.

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
There now, thanks Anjana!
