### ISSUE TITLE
Participating Org Validation Error

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#237]
Hi AidStream Team,

We have been alerted by a publisher to a potential bug on the Participating Organization screen.

They are getting the following error message when attempting to add a participating org:

<img width="636" alt="2" src="https://user-images.githubusercontent.com/46994072/54191356-aa609c80-44ad-11e9-9103-537900ac6f0c.PNG">

The publisher has selected a default language and there is no option to select a different language specifically for this element.

Many thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

Thank you for informing.

We looked into this issue and didn't get it in our side. While we will be eying to this in the future and will surely fix if we come across a similar issue.

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
Hi Anjana,

I have been able to replicate the issue, but only when masquerading on the publisher's own account.

What would you suggest they do to ensure that they can publish their participating Orgs?

Thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

In order to publish the participating organization, they need to publish their activity. Publishing only participating organization is not possible.

Thank you.
Regards,
AidStream Support

**Comment by JoshStanleyDevInit** [comment]
Hi Anjana,

Apologies if my last comment was not clear.

I meant how would you suggest that they can add their Participating Orgs to the Activities that they are building?

Thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

In order to add the participating organization, here is a link provided herewith for your help.
https://github.com/younginnovations/aidstream/wiki/How-to-manage-your-participating-organisation%3F

Following the instruction as per the linked document, one can add their participating Organization to the Activities that they are building.

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
Hi Anjana,

They are adding the Participating Org as per the guidance, but are still seeing the error outlined in my original comment. Can you advise why they are seeing this error?

Many thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

We are trying to detect why they are seeing that error.  As soon as the issue gets detected, we will let you know.

Thank you for your patience.

Regards,
Anjana

**Comment by rupakhetianjana** [comment]
Hello Josh,

The particular organisation was facing the issue because of the failure to save data in their default language. Now the issue has been fixed and they can add/create participating organization.

Thank you!

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
Hi Anjana,

Thanks for making this fix, the organisation has confirmed that they are now able to add their participating orgs.

Josh
