### ISSUE TITLE
A couple of bugs - publishing settings and publishing activities

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#238]
Hi,

The publisher cowi recently wasn't able to publish their activity. This was because of an incorrect API key.

However,

- AidStream wasn't displaying a message that the API key was incorrect. You could enter anything and it said it was valid
- I have now corrected their API key and their activity is published.
- Though on AidStream there is an error mark saying it hasn't published correctly. Saying the activity hasn't actually been published and the user needs to contact AidStream support. When in fact, the activity has been published: https://iatiregistry.org/dataset/cowi-activities 

![image](https://user-images.githubusercontent.com/27764077/54624503-60efee80-4a65-11e9-8049-3d71a69275c9.png)

Please could you have a look into this?

**Comment by manibibek** [comment]
Hi Amy, 

This issue has been fixed now. 

Thank You
