### ISSUE TITLE
Able To Publish Organisation File Without Name Element

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#24]
I was able to publish an organsiation file for CRANE that did not contain the Name element - published file at https://www.aidstream.org/files/xml/ids-org.xml

The name element became mandatory at v2.01 see http://iatistandard.org/201/upgrades/integer-upgrade-to-2-01/migrating/#mandatory-fields-in-organisation-standard

**Comment by sachit-singh** [comment]
I think you are referring to the old [Aidstream](https://www.aidstream.org). Could you please re-confirm. This issue has been taken care of in our new system.

**Comment by wendyrogers** [comment]
I can't recreate this problem at the moment so happy to close for now
