### ISSUE TITLE
Aid Type Vocab 3 Earmarking Modality Needs Drop Down List

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#240]
Hi Aidstream team

When adding an earmarking modality via Aid Type vocab 3 there is no drop down list of options to pick for. The list of allowed values can be found in Appendix 1 of https://reliefweb.int/sites/reliefweb.int/files/resources/Grand_Bargain_final_22_May_FINAL-2.pdf  

(see also http://reference.iatistandard.org/203/codelists/AidTypeVocabulary/)

**Comment by manibibek** [comment]
Hi, 

The codelist has been updated. 

Thank you
