### ISSUE TITLE
Document Link Improvements

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#241]
Hi,

Some users are finding adding document links hard. Here are a few minor improvements that I think could help:

- Please can the title - narrative box in the activity and org pages have a red star to show that it's mandatory?

![image](https://user-images.githubusercontent.com/27764077/55616185-2b4b4500-5789-11e9-936d-4fd413ae2df9.png)

- For an org file, please can the title - narrative box say the word title? 

![image](https://user-images.githubusercontent.com/27764077/55616264-5170e500-5789-11e9-8060-f15de966ebac.png)

**Comment by 77karuna** [comment]
Thanks for pointing out Amy.
We shall surely incorporate them.

**Comment by manibibek** [comment]
Hi Amy, 

The issue has been fixed now.

Thank you

**Comment by amy-silcock** [comment]
This is looking good. I've reviewed the page again, one further suggestion is to remove the red star from document-date. As this element is optional.

Thank you.

**Comment by manibibek** [comment]
Hi Amy, 

We have made the document-date optional and removed the red star. 

Thank you

**Comment by amy-silcock** [comment]
Thank you
