### ISSUE TITLE
Incorrect mandatory location sub-elements

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#242]
Hi, you have a number of mandatory elements within Location that shouldn't be mandatory.

Every direct sub-element within location is optional. Currently on AidStream you can't save the location page unless you've filled out:

- location reach
- location id
- administrative
- exactness
- location class
- feature designation

Please can this be corrected.

**Comment by manibibek** [comment]
Hi Amy, 

This issue has been fixed. 

Thank you

**Comment by amy-silcock** [comment]
Thank you - I've checked on AidStream and it is working correctly.
