### ISSUE TITLE
Internet Explorer related issue

### ISSUE THREAD

**Issue by rupakhetianjana** [younginnovations/aidstream#248]
UI issue
- [ ] Validation by drop-down menus (e.g. selection of participating organisation) should work.

General issue
- [ ]  Internet Explorer warning about data may get stolen in version IE 11.0.110 . 
![image001](https://user-images.githubusercontent.com/42827731/57206975-a3579580-6fe9-11e9-8697-ccef0bc28d23.png)

**Comment by manibibek** [comment]
We will look into this issue on https://github.com/younginnovations/aidstream/issues/194
