### ISSUE TITLE
Registration Agency-XR-EUCB

### ISSUE THREAD

**Issue by PetyaKangalova** [younginnovations/aidstream#254]
Hi Aidstream team,

Please can the Registration Agency XR-EUCB be added to Aidstream?

This is for the European Union Corporate Bodies authority list - http://org-id.guide/list/XR-EUCB

Thank you,
Petya

**Comment by 77karuna** [comment]
Hi Petya,

We shall add the Registration Agency XR-EUCB to AidStream, and notify you when it is done.

Thank  you,
Karuna

**Comment by manibibek** [comment]
Hi Petya, 

The Registration Agency XR-EUCB has been added to Aidstream. 

Thank You
