### ISSUE TITLE
Registration Agency: BJ-IFU

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#265]
Hi AidStream team,

Please can the following Registration Agency be added to Aidstream. This agency was added by Org ID some time ago but I cannot see that it has been requested to be added to AidStream as well.

Org ID page: http://org-id.guide/list/BJ-IFU

Code:  BJ-IFU
Name: The Benin 'Unique Fiscal Identifier'
Country: Benin
Description: The Benin 'Unique Fiscal Identifier' was created by Decree No 2006-201 of 8 May 2006, and is linked to a national directory of persons, institutions and associations.

Thank you

**Comment by manibibek** [comment]
Hi @JoshStanleyDevInit 

The Registration Agency BJ-IFU has been added to AidStream. 

Thank you
