### ISSUE TITLE
In Transaction, future dates must be allowed for incoming and outgoing Commitments. 

### ISSUE THREAD

**Issue by rupakhetianjana** [younginnovations/aidstream#267]
### In Transaction, future dates must be allowed for incoming and outgoing Commitments.

- [ ] Transaction Date

**Comment by 77karuna** [comment]
@amy-silcock 

Hi Amy,

Hope you are doing well. We have a slight confusion whether the transaction-date are possible to set in future date or not.

According to the standard,
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/transaction-date/
@iso-date
This attribute is required.
This value must be of type xsd:date.
`transaction-date/@iso-date must not be in the future.`

Looking forward to your reply.

Thanks,
Karuna

**Comment by rupakhetianjana** [comment]
According to IATI response,

_Transaction dates should indeed never be in the future. A Commitment transaction should be reported with the date that the commitment was made. When this commitment is then realised in the future, it should be added as another transaction (i.e. as a disbursement), when this actually occurs._
