### ISSUE TITLE
Extra decimal places being added to transaction values

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#269]
Hi AidStream,

The British Council have highlighted a potential issue with the csv transaction importer.

Some values are having extra decimal places added to them, despite the value in the csv file being correct.

For example, the following data was loaded to AidStream using the importer:

![image](https://user-images.githubusercontent.com/46994072/59346832-1ea81780-8d0b-11e9-8595-a172e3a41177.png)

But this was originally displayed in AidStream as follows (this has since been manually amended):

![image](https://user-images.githubusercontent.com/46994072/59346891-3f706d00-8d0b-11e9-83d9-857fbd8f67d9.png)

Please can this be looked into?

Thanks,
Josh

**Comment by rupakhetianjana** [comment]
Hello Josh,

We have created the CSV file and tested every possible result, the amount is being imported as it is without extra decimal. So if you could provide the CSV through which the error has been reported, we could solve the issue.

Looking forward to your response.

Regards,
Anjana

**Comment by JoshStanleyDevInit** [comment]
Hey Anjana,

Thanks for looking into this!

Please find the original csv attached. The values hightlighted in BLUE are the ones which are in the csv as .00 but have been output in the XML as .0000000

Many thanks,
Josh
[simple_transaction SPHEIR_06Jun2019 uploaded_errors highlighted (2).xlsx](https://github.com/younginnovations/aidstream/files/3349824/simple_transaction.SPHEIR_06Jun2019.uploaded_errors.highlighted.2.xlsx)

**Comment by sonikabaniya** [comment]
Hello Josh,

We looked into the file that you have provided. Sorry if we were unclear before but you are trying to import "xlsx" file type, Aidstream only supports CSV file import for now. So, you are getting the inappropriate result. Please try to import CSV file and write us back if there is any problem. And apologies for the late response.

Regards,
Sonika

**Comment by JoshStanleyDevInit** [comment]
Hi Sonika,

Thanks for the explanation - I should have checked that myself!

I'll pass this on to the publisher.

Thanks,
Josh
