### ISSUE TITLE
Sectors Showing As Blanks On Activity Screen

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#27]
When viewing activity GB-COH-01926828-ET66/67 the Sector elements has two blank elements?

![image](https://cloud.githubusercontent.com/assets/5500787/14017068/7c29aa60-f1bc-11e5-96a1-61cd012388ef.png)

Has data been migrated incorrectly?

**Comment by anjesh** [comment]
It appears that the old AidStream also doesn't contain the sector values during edits. However the view page shows the values - could be issue with the migration in the old AidStream. Will explore on this and see if this could be fixed.

**Comment by sachit-singh** [comment]
This issue has been fixed.
