### ISSUE TITLE
Registration Agency: NP-IRD

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#271]
Hi AidStream team,

Please can the following Registration Agency be added to Aidstream:

Org ID page: http://org-id.guide/list/NP-IRD

Code: NP-IRD
Name: Nepal Inland Revenue Department
Country: Nepal
Description: The Inland Revenue Department is responsible for the administration of Value Added Tax, Income Tax, and Excise Duty. In the performance of these duties it maintains a register of Permanent Account Numbers (PANs) the unique taxpayer identification number for Nepal.

Thank you

**Comment by manibibek** [comment]
Hi @JoshStanleyDevInit, 

The Registration Agency has been added to Aidstream. 

Thank you
