### ISSUE TITLE
Incorrect Segmentation Guidance

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#277]
Hi AidStream,

When a prospective publisher first signs up to AidStream, they are asked if they would like to have their activities 'Segmented' or 'Unsegmented'.

IATI's guidance is that activities are only segmented if the total size of the activities is >40mb.

So, we should be encouraging publishers **not** to segment their data, if possible.

This is not what is currently advised in AidStream:

![image](https://user-images.githubusercontent.com/46994072/60023361-91ab7980-968d-11e9-9257-762a125c09a8.png)

Please can this text be changed so that it instead says "IATI recommends that you do not segment your data into separate files".

Many thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh, 

This issue has been addressed by changing the text. 

Thank you
