### ISSUE TITLE
Registration Agency: XI-BRIDGE

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#278]
Hi AidStream team,

Please can the following Registration Agency be added to Aidstream. This agency was added by Org ID some time ago but I cannot see that it has been requested to be added to AidStream as well.

Org ID page: http://org-id.guide/list/XI-BRIDGE

Code: XI-BRIDGE
Name: Basic Registry of Identified Global Entities
Country: N/A
Description: Led by three nonprofit partners – Foundation Center, GlobalGiving, and GuideStar – BRIDGE assigns a unique identification number, known as a BRIDGE number, to individual social sector entities around the world. Each 10-digit BRIDGE number is randomly generated and unique to an organization.

Thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh, 

The Registration Agency has been added in Aidstream. 

Thank you
