### ISSUE TITLE
Display Activity Identifier On Main Activity Screen

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#28]
As the activity identifer is unique to each activity please could it be displayed on the main activity screen?

![image](https://cloud.githubusercontent.com/assets/5500787/14017097/c6d540ba-f1bc-11e5-9197-63e0deb1c713.png)

In fact it would be useful if the key attributes of most information could be displayed on the main screen, activity dates, contact info, flow type, aid type, etc so you don't have to go in to edit each element to see what it is set to?

**Comment by pradhanrak** [comment]
This issue will be followed up on issue #49
