### ISSUE TITLE
Bug in Partner Organization

### ISSUE THREAD

**Issue by rupakhetianjana** [younginnovations/aidstream#281]
- [x] Organisation identifier in partner organization suggests that special character isn't accepted.

[IMAGE](https://p14.zdusercontent.com/attachment/74376/wkwnNDrAPfbHeD2Fi0b8X3S0c?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..dZYWwSynUdCpkDyfp8iI0w.2xdn63BBk18aGonVLeYABZUgVLNpYAPZv8m-srmIwvE46njZ0x_-ltD_yc3a9xnBDeKUwViiCNcHEpX8CwFWI0Wu24gTmZAaNyk8Bs8cMpxqfVpjNgYr72nldjVmZNzxrCsCb19Rz4bqc6cMCCETALM280o4uPklMVR8yl1E90nDfDsURN4gMkLPJfy39JCME7tuAafeCY1OLhPa5GLvenKxWCixP8NJ9UHcrab5QcOKKIbIG_OEQtRcytBlC7HF6KWwzQn3vCglC2auQFWJ-A.c2pySfvUBEJEOjlRD99_aw)

**Comment by sonikabaniya** [comment]
This issue has been solved.
