### ISSUE TITLE
Validation On Transaction Required Sector

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#29]
When updating a transaction on activity GB-COH-01926828-TZ21 the transaction validation required that I enter a Sector code on the transaction. However, sector is not mandatory for a transaction unless it is not present at activity level (there is a sector code present at activity level) and then must be present for all transactions - http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/sector/

**Comment by RajbanshiNeha** [comment]
Validation of sector code of required has been removed. However, if sector vocabulary is selected then sector code is required.

**Comment by pradhanrak** [comment]
In addition to what @RajbanshiNeha has said, AidStream has made the sector element required at the activity level and optional at the transaction level. We are hoping with this, the system becomes easier to use for its users.
