### ISSUE TITLE
XM-OCHA Registration Agency listed incorrectly

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#293]
The XM-OCHA Registration Agency (United Nations Office for the Coordination of Humanitarian Affairs) is incorrectly listed as 'XM-OCHAS'.

This means that when output in the XML, it is not matching the Org ID in the IATI Registry.

Please can this be fixed so that 'XM-OCHA' is listed and output instead?

Thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh, 

Thank you for informing us about the issue. The Registration Agency is now listed correctly. 

Thank you

**Comment by JoshStanleyDevInit** [comment]
Hi,

I am reopening this because I have noticed that XM-OCHAS is still output in the interface and in the resulting XML, instead of XM-OCHA:

![image](https://user-images.githubusercontent.com/46994072/65026150-e4fd3300-d92f-11e9-8762-5a283d762ee2.png)

![image](https://user-images.githubusercontent.com/46994072/65026178-edee0480-d92f-11e9-9d84-091928b1e41e.png)

![image](https://user-images.githubusercontent.com/46994072/65026202-fb0af380-d92f-11e9-975f-c1921d58e3ad.png)

**Comment by JoshStanleyDevInit** [comment]
@manibibek  Please can you reopen this for me? :)

**Comment by sonikabaniya** [comment]
Hi Josh,

We looked into it, yes it has been mistaken. We are working on it. You will get informed once it is done.

Regards,
Sonika

**Comment by JoshStanleyDevInit** [comment]
Thanks @soneeka!

**Comment by 77karuna** [comment]
Hello Josh,

The XM-OCHA Registration Agency (United Nations Office for the Coordination of Humanitarian Affairs) is correctly listed. _(not  XM-OCHAS)_

Hope this is ok now.

Regards,
Karuna
