### ISSUE TITLE
Password reset case sensitive

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#299]
The password reset function only seems to work if the user inputs the exact email address that is stored on the user account, including casing.

So (assuming Joshua.Stanley@DevInit.Org was on my account), joshua.stanley@devinit.org would would return "We can't find a user with that email", whereas Joshua.Stanley@DevInit.Org would match, and send the reset email.

Can this be fixed so that it is not case sensitive?

Thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh, 

Thank you for pointing this issue. It has now been fixed. 

Thank you
