### ISSUE TITLE
When adding an extra sector, the dropdown does not appear

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#30]
When adding an extra sector, a new form element appears but the dropdown for sector codes does not work:
![2016-03-31_15](https://cloud.githubusercontent.com/assets/223935/14178001/179e60ac-f759-11e5-932d-db09e2440011.png)

Once you select another sector vocabulary (and maybe switch back afterward), the dropdown appears as well.

**Comment by sachit-singh** [comment]
This issue has already been solved.

Thank you.
