### ISSUE TITLE
Add New Cash Codelist into options for default-aid-type

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#302]
Hi Aidstream Team

Now that the new codelist for [cash and voucher modalities](http://reference.iatistandard.org/203/codelists/CashandVoucherModalities/) has been added into the IATI Standard please could Aidstream be updated so that the new codelist can be used (via default-aid-type at both activity and transaction level)

Many thanks

**Comment by 77karuna** [comment]
Hi Wendy,

Thank you for updating us with the recent changes.
We will definitely integrate it in AidStream.

Regards,
Karuna

**Comment by manibibek** [comment]
Hi Wendy, 

The Cash and Voucher Modalities codelist has been added to both Activity and Transaction Level.

Thank you
