### ISSUE TITLE
Upload XML file requires XML declaration 

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream#305]
See https://github.com/OpenDataServices/cove/issues/1206

I uploaded an XML file with no declaration: 

> \<?xml version="1.0"?\>

or

```
<?xml version='1.0' encoding='utf-8'?>
```

Aidstream does not accept this XML file

@bjwebb notes:

> Including the XML declaration is a SHOULD (not a MUST) in the XML spec https://www.w3.org/TR/xml/#sec-prolog-dtd. Aidstream should accept files without it, so we should report a bug.

Therefore, it might be an idea for Aidstream to not be so strict for XML fie import

(We will however adjust our XML files to include this!)

**Comment by sonikabaniya** [comment]
Hello Steven,

We looked into the issue you stated and yeah we will work on this one very soon. Many thanks for pointing this out. 

On behalf of AidStream team,
Sonika

**Comment by manibibek** [comment]
Hi Steven, 

The issue has been fixed now. 

Thank you

On behalf of AidStream team, 
Mani
