### ISSUE TITLE
Fields being used in Aidstream

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream#31]
We noticed Aidstream does not make use of all fields in IATI, but rather a subset. Is this done by design and will you add the full monty of IATI soon?

**Comment by rolfkleef** [comment]
And maybe issue #2 (still open) is related?

**Comment by pradhanrak** [comment]
@siemvaessen AidStream has all elements except crs-add and fss. When organisations create their account, not all the elements are shown, they have to go to their settings page and check elements they want to fill out. May be that is the reason you did not see all of the elements? Please do let us know if you find any element missing. I will close this issue for now.
