### ISSUE TITLE
Registration Agency: YE-MSAL

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#311]
Hi AidStream team,

Please can the following Registration Agency be added to Aidstream. This agency was added by Org ID some time ago but I cannot see that it has been requested to be added to AidStream as well.

Org ID page: http://org-id.guide/list/YE-MSAL

Code: YE-MSAL
Name: Ministry of Social Affairs and Labour
Country: Yemen
Description: The Ministry of Social Affairs and Labor, Social Development Sector, issue licenses for the operation of associations, civil organisations and unions.

Thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh, 

The Registration Agencies are now automatically imported from org-id.guide on a daily basis. So, YE-MSAL has been already added to Aidstream. 

Thank you,
Mani

**Comment by JoshStanleyDevInit** [comment]
Hi Mani,

Thanks for getting back to me. Unfortunately I still seem to be unable to add YE-MSAL as an agency; see below:

[cid:image001.png@01D58286.6A2A4000]

Thanks,
Josh

**Comment by manibibek** [comment]
Hi Josh,

I couldn't see the image attached. Can you please attach the image again directly from Github? 

Thank you

**Comment by JoshStanleyDevInit** [comment]
Hi Mani,

Apologies, here it is:

![YE-MSAL](https://user-images.githubusercontent.com/46994072/66747076-88802b80-ee7b-11e9-9ccd-b7879a5855f7.png)

**Comment by manibibek** [comment]
Hi Josh,

Thanks for sending us the photo. This issue is related to the settings page and we are currently working on it. We will notify you after it has been done. 

Regards, 
Mani
