### ISSUE TITLE
Policy Marker- unable to enter code for vocabulary 99

### ISSUE THREAD

**Issue by PetyaKangalova** [younginnovations/aidstream#312]
Hi team,

This issue has just been flagged by a publisher. I also checked into my account and it does look like it is a bug on Aidstream.

If an organisation selects vocabulary  `99- Reporting Organisation,` they should be able to to add their own Policy Marker code. Currently that is not possible (see screenshot below).
![image](https://user-images.githubusercontent.com/24607542/66761823-af028e80-ee9c-11e9-941f-8d4547605bad.png)

Organisations should be able to enter/type their own code if they select  `99- Reporting Organisation`.

Could you look into this?

Thanks,
Petya

**Comment by PetyaKangalova** [comment]
Hi team,
Is there an update on this? Léonore Rougemont from Drugs for Neglected Diseases initiative has been in contact with me again as they are awaiting this fix to be able to publish data to IATI.
Thanks,
Petya

**Comment by 77karuna** [comment]
Hello Petya,

Hope you are doing well.

If an organisation selects vocabulary **99- Reporting Organisation**, they are now able to to **add their own** Policy Marker code. 

Regards,
Karuna
