### ISSUE TITLE
XI-BRIDGE unavailable on Organisation Finder

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#313]
A publisher has got in touch to advise that they are trying to add Community Initiatives for Rural Development (https://iatiregistry.org/publisher/ciford-) as a participating organisation to one of their activities.

CIFORD are yet to publish themselves but when using the Organisation Finder function to add them, the [XI-BRIDGE Identifier](http://org-id.guide/list/XI-BRIDGE) is not available in the list:

![image](https://user-images.githubusercontent.com/46994072/70046691-6de64b00-15be-11ea-86d7-e219324d5972.png)

Please can this be added?

Thanks!

**Comment by 77karuna** [comment]
Hello Josh,

XI-BRIDGE organisation is now available on Organisation Finder interface. 

Thanks.

Warm regards,
Karuna
