### ISSUE TITLE
BUG - Users can't input their own recipient-region codes

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#316]
Hi AidStream,

When entering a `<recipient-region>` users can only select a DAC region code. This is correct when using vocabulary 1 (DAC) or no vocabulary.

However, when the vocabulary is changed to 2 (UN) or 99 (org's own) there's no option to enter your own code.

Please can this functionality be added?

**Comment by sonikabaniya** [comment]
Hi Amy,

We looked into issue you pointed, thank you for mentioning this. We are working on this and will get back to you once it is done. 

On behalf of AidStream,
Sonika

**Comment by amy-silcock** [comment]
Thank you @soneeka!

**Comment by sonikabaniya** [comment]
Hi Amy, 

This issue has been fixed. You can check it from your side. 

On behalf of AidStream team,
Sonika

**Comment by amy-silcock** [comment]
Hi @soneeka, the fix is perfect. Thank you.
