### ISSUE TITLE
AidStream Website Down?

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [younginnovations/aidstream#318]
aidstream.org is currently unavailable for me and my Tech Team colleagues. We are getting the following when we try to access the website:

![image](https://user-images.githubusercontent.com/46994072/86228820-c696ba00-bb86-11ea-96e6-37786afce6c8.png)

Please can this be looked into?

Thanks!

**Comment by manibibek** [comment]
We faced a minor issue and we are looking into this. We will get back to it quickly. 

Thanks

**Comment by manibibek** [comment]
Hi Josh, 

The issue has been resolved now and the website is loading fine. Thanks again.
