### ISSUE TITLE
Links to guidance pages

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#319]
Hi, great to see there are now links to IATI guidance pages on AidStream!

![image](https://user-images.githubusercontent.com/27764077/90793210-59d8aa00-e303-11ea-8a11-17c7e6e50f2b.png)

Please could the links be updated to our corresponding web pages rather than the older pdfs on google drive?

You can find all of the relevant pages listed here: https://iatistandard.org/en/guidance/standard-guidance/
Our plan is to keep adding more as they get consulted on and finalised.

**Comment by sonikabaniya** [comment]
Hi Amy, thank you for mentioning this. We have updated accordingly, please verify it from your end.

**Comment by 77karuna** [comment]
Hi Amy,

The links to the guidance page have been updated.
Thank you for your support. @amy-silcock 

Best regards,
Karuna

**Comment by amy-silcock** [comment]
Thank you both!
