### ISSUE TITLE
Exact location 

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream#32]
We see "GEOPOLITICAL INFORMATION" and the options to choose a country/region w narrative, we are unable to spot the field where we can add and exact geo-location for an activity. Is this hidden or not available?

**Comment by rolfkleef** [comment]
Hi Siem, have you checked "Location" in the settings under "Choose elements to show/ hide"?
https://aidstream.org/settings

There should be a separate link "Location" under "Geopolitical information" in the right-hand column then.

**Comment by siemvaessen** [comment]
Aha! 

Thanks @rolfkleef , could you also tell me if all IATI fields are availble yet?

**Comment by rolfkleef** [comment]
I don't know about that, I think it was discussed in a check-in call. Maybe specify what you miss under that issue (#31) and we could discuss the roadmap in the next call (scheduled coming Wednesday).
