### ISSUE TITLE
page not found error

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#320]
Hi AidStream

A user has got in touch to say they're getting a 'page not found' error when trying to publish an activity. I also get the same error when trying to access their activity.

Everything looks okay from the IATI Registry end.

The organisation is Faith to Action Network. 

Please can you look into this?

**Original message is:**
---
To whom it may concern,

I am trying to publish my data but when I click add activity I get this error

Kindly support

Best wishes

----
Programme Manager
Faith to Action Network

**Comment by manibibek** [comment]
Hi Amy, 

Thank you for notifying us about this issue. There was a small bug in the system which has been addressed now. 

Please check from your end and don't hesitate to reply back if you face any further issues. 

Regards,
Mani

**Comment by amy-silcock** [comment]
Thanks @manibibek!

It's working for me and I'll let the user know.
