### ISSUE TITLE
Update  IATI region codelist

### ISSUE THREAD

**Issue by PetyaKangalova** [younginnovations/aidstream#321]
Hi Aidistream team,

I am supporting a user and noticed that the region codelist is not up-to-date. 

![image](https://user-images.githubusercontent.com/24607542/93889125-bce1a600-fce0-11ea-8a13-6987e0e0eb23.png)
The codelist was relatively recently updated. See here: https://iatistandard.org/en/iati-standard/201/codelists/region/
Do let me know once it has been updated.

Many thanks!

**Comment by 77karuna** [comment]
Hi Petya,

The codelist of the Recipient Region has been updated.

![Screenshot-from-2020-09-25-10-54-41](https://user-images.githubusercontent.com/43775456/94228848-ac6a3f00-ff1d-11ea-824a-4144364f258b.png)

Thank you @PetyaKangalova .

Good day!

Regards,
Karuna
