### ISSUE TITLE
Activity Date Bug

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#322]
Hi all,

A user has come across a bug with the activity date logic in AidStream.

They have an activity which was stopped early due to COVID. However, they're not able to add an 'actual end date' which is before their 'planned end date'. I've tested this and it's not working for me either.

Their 'actual end date' is after the start date, and is not in the future. Their screen shot is below. Their dates work and should be allowed.

Please can you look into this?

![image](https://user-images.githubusercontent.com/27764077/94413238-b9cc3700-0172-11eb-9157-9f6368f96e9c.png)

**Comment by 77karuna** [comment]
Dear Amy,

The issue reported has been resolved.

Thank you.

Regards,
Karuna
