### ISSUE TITLE
Bug: Transactions don't need a unique reference

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#323]
The transaction reference is optional so doesn't have to be completed, nor does it have to be unique (though logically it should be).

However, multiple transactions with blank references should be allowed. I've tested this and it throws the error shown below. Please can this be fixed? 

![image](https://user-images.githubusercontent.com/27764077/97857434-a40fdb80-1cf5-11eb-8235-9208e243d257.png)

**Comment by Beecallpaw** [comment]
This issue has been resolved.
