### ISSUE TITLE
Security issue: one user can change other users and their actvities

### ISSUE THREAD

**Issue by siemvaessen** [younginnovations/aidstream#33]
I can change anything from anybody: https://aidstream.org/activity/700 - not mine, but was able to add 0000 as Other identifier. This was raised back in 2014 (!) on the previous Aidstream version: https://github.com/younginnovations/aidstream/issues/97 

Sad to see its re-introduction. FIX ASAP!!

**Comment by anjesh** [comment]
Thanks @siemvaessen for flagging this. It's a huge overlook from our end. This has been fixed and deployed.
