### ISSUE TITLE
Order in the list of activities?

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#34]
It's not clear to me how to ordering of the list of activities is done.

Sometimes, when editing a field in an activity, the activity is pushed to the bottom of the list. Sometimes, it's not. Some experiments in our openforchange activities list, with chronological order numbered:
![2016-04-11_01](https://cloud.githubusercontent.com/assets/223935/14425876/f6f3d298-ffea-11e5-8ed0-77d018436b7d.png)

The effect is that the S.N. changes upon reordering, so it's basically just a line number and not an identifier although it looks like one (not sure what "s.n." stands for).

Maybe it would be good to enable a user to sort the columns, based on title, last update, status?

**Comment by MettePfeiffer** [comment]
We have the same issue regarding the order of the list of results. It seems random what order they are listed, and sometimes an update changes the order, sometimes it does not. It would be nice to be able to sort the lists yourself, as suggested by Rolf.

**Comment by pradhanrak** [comment]
@rolfkleef There was no sorting logic defined for the list of activities. We have changed that to sort by latest updated date. We are working on the feature you suggested and enabling the users to sort based on title, last update and status.
@MettePfeiffer We will add the sorting feature to all listing of results and transactions as well.

**Comment by imlunek** [comment]
We have added the sorting feature for **Activities**, **Results** and **Transactions**. By default:
- **Activities** gets sorted by **last updated date and time** in descending order.
- **Results** gets sorted by **result title** in descending order.
- **Transactions** gets sorted by **transaction date** in descending order.
