### ISSUE TITLE
Add new registration agency: NE-DGI

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/aidstream#341]
A new registration agency ([NE-DGI](https://org-id.guide/list/NE-DGI)) has just been added to the org-id.guide website for the Niger Tax Directorate. Can we add this to AidStream so that new publishers can use it to register? Thanks

**Comment by emmajclegg** [comment]
@BibhaT - to let you know about this new org-ID request for AidStream. I am supporting an AidStream publisher who will likely need to register with "NE-DGI" soon. 

To note, this was added to AidStream a few years back (e.g. publisher "Timidria" used it), but is no longer in the Registration Agency dropdown list in Settings.

**Comment by BibhaT** [comment]
We're working on it right now. I'll let you know after it's complete.

**Comment by BibhaT** [comment]
@emmajclegg the list has been updated. NE-DGI is now available on AidStream. 

P.S. We've shifted from GitHub so please tag me when creating new issues. This way I get notified and the issue doesn't gets missed. Thanks.

**Comment by emmajclegg** [comment]
Thanks Bibha - I can see the change in AidStream, much appreciated
