### ISSUE TITLE
Download data as IATI XML before publishing

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#36]
In the previous version of AidStream it was possible to download a "raw data" file with all activities in IATI XML format, before they are published. This is very useful to provide feedback and visualisations in the process  of getting their data in shape.

In the current version, this "download as IATI" option is no longer available.

Could it be made available again, perhaps with only activities in status "completed, verified, published"? Once in status "complete", an activity contains the necessary fields to provide technically valid IATI XML.

**Comment by sachit-singh** [comment]
This feature has already been implemented into AidStream.

**Comment by rolfkleef** [comment]
No it hasn't been implemented. I can only download published activities now. I want to be able to download my data as XML for verification before I publish them. This was possible in the previous version, but not in the current version (or at least: I don't seem to find it anywhere)

**Comment by sachit-singh** [comment]
@rolfkleef I apologize for mistaking this feature for a different one. This feature will also be implemented in near future. Thank you very much for letting us know.

**Comment by rolfkleef** [comment]
thank you :-)

**Comment by 77karuna** [comment]
Hi Rolf,

Activity XML can be viewed any time regardless of the published status in AidStream.

Regards,
Karuna
On behalf of AidStream Team
