### ISSUE TITLE
Element Reference is non mandatory

### ISSUE THREAD

**Issue by pradhanrak** [younginnovations/aidstream#37]
The IATI standard indicates that Reference fields under the Performance Results is optional, not mandatory.

Changelog - 2.02
The optional reference element was added (From http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/result/indicator/reference/)

This was also already a part of the discussion when this change was proposed. See http://support.iatistandard.org/entries/79784435-Results-Require-unambiguous-indicator-reference

**Comment by TimSchootUiterkamp** [comment]
Thank you for bringing this up. I hope this can be fixed soon, because we are planning to use AidStream to fulfill our reporting obligation to the Dutch Ministry of Foreign Affairs (which needs to happen before the end of this month).

**Comment by pradhanrak** [comment]
@TimSchootUiterkamp We have made the changes to make the Reference Element non-mandatory. You should be able to publish your data to IATI now.

**Comment by MettePfeiffer** [comment]
There seems to still be a hick-up: When trying to mark my activities as complete, I get the following error messages:
"Error 1868:Element 'reference': The attribute 'code' is required but missing.in line no. 69
"Error 1871:Element 'vocabulary': This element is not expected. Expected is ( ##other\* ).in line no. 70"
This respectively whether I filled in the fields (with 99 Reporting organisation and our own code) or not.
Hope you can help, we are also busy preparing our first reporting for the Dutch Ministry of Foreign Affairs.
Best, Mette

**Comment by TimSchootUiterkamp** [comment]
Thank you. I've been able to mark my activity as complete.
