### ISSUE TITLE
Location form always shows warning "leave page?"

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#39]
The page with the location form always shows the pop-up asking to confirm to leave the page, even when nothing is entered or changed.

**Comment by rolfkleef** [comment]
Actually, the Settings page seems to have this issue too: https://aidstream.org/settings

**Comment by pradhanrak** [comment]
@rolfkleef We were concerned about users loosing their data when the reloading or exiting the forms. We understand it gets annoying having to click on leave/reload. We have made changes and updated AidStream but we are still working on this to better this.

**Comment by pradhanrak** [comment]
We have completed this issue. Now the leave/reload pop up shows if there are changes made.
