### ISSUE TITLE
Publishing of XML files to IATI Registry via API

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#4]
The activities go through the workflow (draft->completed->verified-> published). The XML files get generated when it get published. The user may set the configuration to publish to IATI Registry upon publishing or may choose to link to IATI Registry later. 

In any case, the Registry API is called to create or update the datasets (activity xml file) in the registry. 
The documentation of API is [here](https://docs.google.com/document/d/1vB1e4PKw_vOJq6Vhsb_uwRenCHf4_CQPKLt2vMAQEf4/edit#) 

In this issue, we will work on only the create dataset and update dataset APIs only. 

For testing, we can use any existing publisher-id and their API key.

**Comment by RajbanshiNeha** [comment]
While deleting the dataset from IATI Registry, the organization must have authority to delete the dataset.
