### ISSUE TITLE
Location form: "Srs name" not added when clicking on the map

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#41]
The easiest way to add a location would be to click on it on the map. The lat,lon are then filled in, but the field "Srs name" is not. It's unclear what this is or how to find a value for it.

**Comment by pradhanrak** [comment]
@rolfkleef we have filled out the "Srs name" with the value provided here: [http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/location/point/](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/location/point/)
which is http://www.opengis.net/def/crs/EPSG/0/4326
So when we have value for longitude and latitude we just fill the "srs name" attribute for point element.
