### ISSUE TITLE
Two organisations have had their new data published without actively publishing it.

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream#43]
Hello, Bond have had two HelpDesk tickets (3518 and 3500 - Wendy might be able to give you access) from organisations this week, where they saved the data in AidStream without actively going through the steps in AidStream to publish it, but the new data has appeared in their activity file on the Registry. This has concerned them as they wanted to verify it  before they published it. Please check if this is a bug.

**Comment by pradhanrak** [comment]
@SJ-bond could you please assign those tickets to us? currently we don't have access to the tickets.

**Comment by SJ-bond** [comment]
@pradhanrak I have just assigned tickets to AidStream support and cc'd you in.

**Comment by pradhanrak** [comment]
@SJ-bond We might have published the activities for the organisations during testing. But this is not a bug with the system. For the data to be published, it would have to be done manually.

**Comment by anjesh** [comment]
Need to check on this once more.

**Comment by pradhanrak** [comment]
Same as issue #44
