### ISSUE TITLE
data updates publishing to IATI Registry without going through the manual publishing process

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream#44]
Hello, issue #43 update: we've had another organisation reporting this. Are you sure it's not possible that AidStream is automatically updating the file on the Registry when the data is saved?

**Comment by pradhanrak** [comment]
@SJ-bond Could please send us the name of the organisations who had this issue?

**Comment by pradhanrak** [comment]
@SJ-bond I am closing this issue for now. We couldn't find any instance where the data automatically gets published to the IATI Registry. Please re-open this issue if this occurs again.
Thanks.
