### ISSUE TITLE
Display user-friendly error messages for the schema generated errors

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#46]
Currently in the publishing workflow, when the user completes the activity, the activity xml is validated against the schema and the appropriate error messages are shown, which comes directly from the schema. This makes the error very hard to comprehend and follow. The errors are shown in reference to the XML file - which is not yet generated in the flow. We will develop a module that traverses and parses the temporary XML file in which the errors occurred and prepares the error message so that it's not easy to follow and fix by the users themselves.

**Comment by pradhanrak** [comment]
An example: Error message given by Schema Validation when sector code is missing in sector element is: **Error 1868:Element 'sector': The attribute 'code' is required but missing.in line no. xxxx**

Error message the system is will show:
  **The required Sector Code is missing from the ‘Sector’ element.**
When there are multiple Sector Code missing from multiple Sector elements:
  **Multiple Sector Code is missing from 'Sector' elements.**

**Comment by pradhanrak** [comment]
When Transaction date is missing, Schema Validation give following error:
**Error 1871:Element 'value': This element is not expected. Expected is (transaction-date) in line no. xxxx**

Error message the system will show:
  **The required Transaction Date is missing from the 'Transaction' element**
When there are multiple Transaction dates missing, the following message will be shown,
  **Multiple Transaction Dates are missing from 'Transaction' elements**

**Comment by sachit-singh** [comment]
This feature has already been implemented.
