### ISSUE TITLE
Improve Activity View Interface

### ISSUE THREAD

**Issue by pradhanrak** [younginnovations/aidstream#49]
The existing Activity View take a quite of bit of clicking to view all of the information in an activity. To make it easier for the users to view the activity information, the Activity View Interface has been re-designed.
The following design shows the Activity Detail View
![aidstream - activity detail](https://cloud.githubusercontent.com/assets/8123056/15209309/13ea354a-1850-11e6-81f2-de16b9c460ea.png)

When user hovers over 'View in other languages', other language text will show up on in a tooltip.
![view in other language](https://cloud.githubusercontent.com/assets/8123056/15209358/58e3102c-1850-11e6-80be-23130072b0f8.png)

When user clicks on 'Show more info', all the related information will be shown.
![result](https://cloud.githubusercontent.com/assets/8123056/15209364/61a50ecc-1850-11e6-92dd-0cc39d21e5f0.png)

**Comment by sachit-singh** [comment]
This enhancement has been completed.
