### ISSUE TITLE
Show XML view and download functionality for any activity

### ISSUE THREAD

**Issue by pradhanrak** [younginnovations/aidstream#51]
Currently XML is generated when an activity reaches the published state of the workflow. The xml is generated into the file to be published to IATI registry and is not available for every activity individually. This is inconvenient for users who want to view xml for the activity they are working on. So with this feature, users will be able to view and download xml for every activity, individually, at any state of the workflow.

**Comment by sachit-singh** [comment]
This issue has already been implemented into AidStream.
