### ISSUE TITLE
Elements show/hide change

### ISSUE THREAD

**Issue by pradhanrak** [younginnovations/aidstream#53]
The following is the scenario which has brought a confusion regarding elements when changes are made on the elements checklist on the settings page.
- a user checked an element to add in their activities in the settings page.
- user added information for the element in the activities.
- then user unchecked the element on the element checklist on the settings page.

When this happens, the information is already saved in the database, thus the information is added in the xml generated for the activities. Should these information be added in the xml when the element is actually unchecked in the settings?

**Comment by anjesh** [comment]
I think the unchecked elements (the one not appearing in the activity page) should be excluded from the xml file during publishing. If the element is already included, the element will appear there unless manual publishing occurs. 
@wendyrogers what do you think?

**Comment by wendyrogers** [comment]
Thanks @anjesh  and my recommendation would also be that if the element is unchecked in the 'Setting' then it should NOT be included in the XML. However, the values previously provided in the database should also not be deleted in case the element is subsequently reinstated

**Comment by anjesh** [comment]
Yes the elements won't be deleted from the database, but they just won't be shown in the xml during publishing.

**Comment by rolfkleef** [comment]
Agree. I would also propose to change the label on the Settings page from "Choose elements to show/ hide" into "Choose elements to include in your data" to reflect this.

**Comment by pradhanrak** [comment]
@rolfkleef about changing the label, we will make this change as a part of of the improvement in the settings which we are working on.

**Comment by anjesh** [comment]
Fixed.
