### ISSUE TITLE
Removing a budget element from an activity

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#54]
When a user has added a budget to an activity, and then decides to remove it again, it leads to a form validation error.

At a page like https://aidstream.org/activity/1234/budget there is a trash can in the top-right corner that suggests it removes the budget, but you still need to save the form to store it, and then the form complains that mandatory information is missing.

A work-around is to go to the activity overview https://aidstream.org/activity/1234 and click the trash can next to the budget element there, but this is not obvious for users.

Not sure what a good solution would be, perhaps accept a single, completely empty budget form as a valid input meaning "delete the budget element"?

**Comment by pradhanrak** [comment]
@rolfkleef or we could redirect users to the activity overview when they click the trash when there is only a single, completely empty budget element.

**Comment by imlunek** [comment]
In activity overview page, we have added edit and remove button to activity element level section that are visible on hover over individual section.

Click on the remove button will remove the individual element data block. So, users won't come across the problem as @rolfkleef had mentioned for removing budget element.

**Comment by anjesh** [comment]
Implemented for budget.
