### ISSUE TITLE
Confusion about sum total of percentage in recipient country and recipient region elements

### ISSUE THREAD

**Issue by pradhanrak** [younginnovations/aidstream#56]
@wendyrogers on AidStream, when both the recipient country and recipient region are present in an Activity we added a validation so that the sum of percentage of multiple countries in the recipient country element is 100 and same for the sum of percentage of multiple regions in the recipient region element. In the IATI standard document it says ["When both the recipient-region and recipient-country, then the @percentage values should sum to 100% for the specific iati-activity."](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/recipient-region/).
Can you please confirm if we should change the validate to sum of percentage of all countries and regions together to be equal to 100?

Thanks

**Comment by wendyrogers** [comment]
Hi @pradhanrak the rule is that you only ever publish country OR region OR if you publish both (which is only allowed at V2.01 or later) then the percentage of both must sum to 100% combined (eg Bangledesh 50% & South Asia, regional 50%). See http://iatistandard.org/202/activity-standard/overview/geography/

Hope that helps

**Comment by sachit-singh** [comment]
This issue has been solved. Thank you.
