### ISSUE TITLE
Wiki: Bulk activity import guidance is missing guidance on DAC5 sector field 

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream#57]
https://github.com/younginnovations/aidstream-new/wiki/Activity-Creation#2-bulk-activity-import - `Sector_DAC_5Digit` is in the template / list of fields - but there is no written guidance

**Comment by pradhanrak** [comment]
Thank you @stevieflow for letting us know. I have added the instruction for **Sector_DAC_5Digit** in our user guide here, https://github.com/younginnovations/aidstream-new/wiki/Activity-Creation#2-bulk-activity-import
