### ISSUE TITLE
Where do the activity defaults come from

### ISSUE THREAD

**Issue by stevieflow** [younginnovations/aidstream#58]
(discussion via https://github.com/OpenAgFunding/development/issues/12)

It is possible to determine which fields are accessible for an activity within AidStream.

To begin with, certain fields are enables/ticked by default.  

Question - is this default selection informed by anything?  Or - are these defaults just a selection of _likely_ fields ?Any insight/background appreciated

**Comment by anjesh** [comment]
Apologies for getting late on this.

These defaults used to be DFID recommended fields before V2. Now these are mandatory fields + budget and transactions. Now the Aidstream onboarding process for new users take them through these screens to let them know about the presence of the remaining fields. Also i am thinking whether we need to have these information somewhere in the elements listing for quick action by users.
