### ISSUE TITLE
Ability to unlink the published XML file from Registry. 

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#6]
This issue is related to https://github.com/younginnovations/aidstream-new/issues/5 

When the XML files are published and linked to the registry, these files get listed in the IATI Registry. AidStream also lists the published XML files. However when the publishing type is changed from segmentation to unsegmented and vice versa, there will be duplication of activities as new XML files get created. These files should be unlinked from the IATI Registry and there should also be ab option to delete files from AidStream (see https://github.com/younginnovations/aidstream-new/issues/7) 

Scenario:
When the publishing type = Unsegemented, there will be only one xml file publisher_id-activities.xml. When the publishing type is changed to Segmented, now there will be couple of files as per these [rules](https://github.com/younginnovations/aidstream-new/issues/5). When the API is called to link these newly created files to Registry, the previously linked file (i.e publisher_id-activities.xml) should be unlinked from registry. The user should now have option to delete that file from AidStream, as these activities are already present in the segmented XML files. 

https://docs.google.com/document/d/1vB1e4PKw_vOJq6Vhsb_uwRenCHf4_CQPKLt2vMAQEf4/edit#heading=h.tynk2bte4osj doesn't cover the delete API. Need info on that.

**Comment by sachit-singh** [comment]
This feature has already been implemented into AidStream.
