### ISSUE TITLE
Migrate files and documents to Amazon Cloud (S3) 

### ISSUE THREAD

**Issue by RajbanshiNeha** [younginnovations/aidstream#64]
We are planning to host all the uploaded documents and published xml files to Amazon S3 cloud. We will migrate all the existing documents to the cloud and update the system so that any new files uploaded or created from now on, will be directly served from S3. This will ensure the high uptime for the files.

The following tasks have been identified.
- [ ] Setup Amazon S3 account for staging and demo
- [ ] Migrate existing xml files/documents into the Amazon S3 cloud server, tests required
- [ ] Update upload functionality to use S3 for new created files/documents
- [ ] Update the server config (rewrite) to redirect the existing xml files/documents to the amazon S3 url
- [ ] Tests working of all the existing files so that registry doesn't get file-not-found error for linked xml files

**Comment by anjesh** [comment]
Moved all the files to google cloud maintaining the same file structure.
