### ISSUE TITLE
Space Included At Start of Reporting Org Ref

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#66]
The published XML file produced for Red Cross Red Crescent Climate Centre currently contains reporting-org @ref with a space prefixing the organisation identifier see http://climatecentre.org/downloads/files/rcccadmin-activities.xml

eg <reporting-org type="21" ref=" NL-KVK-27267681">

Can this be prevented by always ensuring that the org. identifier is 'trimmed' of any leading or trailing spaces?

**Comment by RajbanshiNeha** [comment]
This issue has been solved.
