### ISSUE TITLE
No Facility To Set The Humanitarian Attribute On iati-activity

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#67]
If I edit the activity identifier field I do not have the facility to set (or unset) the humanitarian attribute for iati-activity see http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/. This is required to indicate that the activity is a 'humanitarian' activity.

Please can this be added (or is it set elsewhere?)

**Comment by wendyrogers** [comment]
Have found it now in 'override activity defaults'. However, still wondering if this should also be available with the other activity identifier fields or somewhere more prominent so that the user is prompted to consider if it should be set or not? Other users any thoughts?

**Comment by wendyrogers** [comment]
Hi Aidstream team just updating this issue with regard to potentially having the humanitarian flag moved from within the activity defaults to perhaps next to the activity 'Title' to make it much more prominent for users to set if appropriate. Many organisations are publishing a mix of both humanitarian and development activities and as part of the Grand Bargain we are trying to get publishers to use the specific humanitarian elements whenever appropriate. 

Also would it be possible to flag the use of the humanitarian scope field (although not mandatory) if the humanitarian flag has been set? I would be very interested in your thoughts and any suggestions for making these features more prominent.

**Comment by 77karuna** [comment]
Hi Wendy,

Hope you are doing well.
We have updated AidStream such that organisations can now identify humanitarian activities with ease.
As humanitarian scope is not mandatory, an information is provided if humanitarian flag is set.

Thanks.

Regards,
Karuna

**Comment by wendyrogers** [comment]
Great and many thanks for the update Karuna!
