### ISSUE TITLE
Extra Validation Required For Humanitarian Type and Humanitarian Scope Vocab

### ISSUE THREAD

**Issue by wendyrogers** [younginnovations/aidstream#69]
Extra validation is required between the Humanitarian Type and Humanitarian Scope Vocabulary fields. If a user selects a humanitarian type of 1  then they should only be able to select from the values on the Humanitarian Scope Vocabulary where the code starts with '1-' or is '99'. Similarly if a humanitarian type of 2 is selected then the user should only be able to select a vocabulary which starts with '2-' or is 99

**Comment by sachit-singh** [comment]
Thank you @wendyrogers. This issue has been solved.
