### ISSUE TITLE
CSV import: valid values for booleans

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#78]
The template has a column for the `Humanitarian` field. This is of type xsd:boolean, but only seems to accept `0`, `1`, or nothing. It would be good if it can also accept `no`, `NO`, `false`, `yes`, `true`, and so on.

**Comment by maharjanraj** [comment]
@rolfkleef we have added 0,1, yes, no, true, false,etc. for both upper and lower cases for the boolean cases. Thank you for the feedback.
