### ISSUE TITLE
CSV import: multiple budgets

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#80]
The CSV import currently doesn't allow for multiple budget lines per activity. However, it is recommended to split a project budget per year or per quarter, so it should be possible to upload multiple budget lines per activity.

**Comment by SJ-bond** [comment]
Hi - I'm working with organisations that need this feature too.

**Comment by maharjanraj** [comment]
@rolfkleef Budgets can now be added multiple times per activity. Thanks for the feedback.
