### ISSUE TITLE
Related activities data not uploading when using template Activity with Other Fields

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream#84]
Hello, I've been using the Activity with Other Fields template this week to upload activity data, and I noticed that the data in the Related Activity element did not successfully upload using this template - the rest of the data in the template uploaded fine and there were no error messages on uploading the data. I know this is a newly added element to this template - is it possible for you to take a look and make a fix if needed? Please advise timeframe for fix as we are using it with a client to upload UK DFID and NL MFA data and they are both on deadlines. Thank you! cc @anjesh

**Comment by maharjanraj** [comment]
@SJ-bond the issue has been fixed. Thank you!
