### ISSUE TITLE
No "View activity" button in Transactions and Results

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#86]
When looking at details of an activity (Title, Description, Sector, etc) there is a "View Activity" button in the top-right, to go back to the activity summary screen (for instance to mark edits as completed).

In the Transactions and the Results areas, this button is not there. Would be useful there too!

(A work-around is to click on another section, then on the "View Activity" button)

**Comment by sachit-singh** [comment]
This issue has been fixed.
