### ISSUE TITLE
Error: User reached or exceeded his exchangeRates API request

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream#87]
Hello, one of the organisations I work with saw this error message when they tried to publish their data on Wednesday 4 January. 

**User has has reached or exceeded his exchangeRates API request**

I've not seen this error message before so I am sharing it here in case you need to take any action. Screenshot attached:
![api_exceeded_anonymised](https://cloud.githubusercontent.com/assets/8158574/21719213/65631d30-d414-11e6-932b-febf439ea03b.png)

Thank you, Sarah

**Comment by sachit-singh** [comment]
Hello. This issue has been fixed. Would you try and publishing it once again and let us know if you encounter any errors.

Thank you.
