### ISSUE TITLE
transaction/provider-org/@type and transaction/receiver-org/@type should use an OrganisationType codelist dropdown

### ISSUE THREAD

**Issue by andylolz** [younginnovations/aidstream#88]
`transaction/provider-org/@type` and `transaction/receiver-org/@type` both allow freetext rather than insisting types come from the `OrganisationType` codelist. Validation doesn’t appear to catch this, either when saving the transaction or when marking the activity as complete.

**Comment by sachit-singh** [comment]
@andylolz Thank you very much. Your assistance is much appreciated.
