### ISSUE TITLE
Using the XML import: issues with 1.03 data

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream#92]
Hi, the XML import is struggling to import data in 1.03 version of the Standard (this is where a user is switching from CSV Convertor to AidStream). The error message they receive in AidStream doesn't really help (see screenshot attached). Is it possible to fix this please?
![aidstream upload activities](https://cloud.githubusercontent.com/assets/8158574/23411656/de9a8dd4-fdca-11e6-9a9b-e3af790391bf.png)

**Comment by shresthaKiran** [comment]
Hello SJ-bond, could you please send us the xml file you tried to upload.

**Comment by SJ-bond** [comment]
This is the XML file: [https://www.sightsavers.org/wp-content/uploads/2017/02/IATIActivityFileQ42016.xml](url)

**Comment by shresthaKiran** [comment]
It has been fixed. Could you please try uploading it again in AidStream.
