### ISSUE TITLE
New user registration remarks

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#94]
I had the pleasure of going through the "new user registration" flow, setting up a test account for myself. Works well!

Two small remarks:

In step 3 of the sign-up, the layout of the third step seems a little off:
![2017-04-17_01](https://cloud.githubusercontent.com/assets/223935/25099399/66888776-23ac-11e7-8ff4-522a13dadf5d.png)

And after I click the confirmation email, I see two copies of the same text but without the "promised" account information:
![2017-04-17_02](https://cloud.githubusercontent.com/assets/223935/25099429/7f338618-23ac-11e7-88b8-40046efd5abe.png)

**Comment by rupakhetianjana** [comment]
Hello rolfkleef,

The changes have been made. Thank you for the suggestion.

Anjana
