### ISSUE TITLE
Zero values in imported results are not used

### ISSUE THREAD

**Issue by rolfkleef** [younginnovations/aidstream#95]
When I import results, values of zero end up as "Not available" in AidStream, and completing an activity is not possible with the error message:

`Multiple Baseline Code are missing from the ‘Baseline’ element. of Description element.`

The error message is not very clear, but in the XML output it says: `Error 1868:Element 'baseline': The attribute 'value' is required but missing.in line no. ..`

If I edit the results one by one, the zero values are present, and simply clicking save without any changes then saves it as zero value. After doing that for each result with a zero, it is possible to mark the activity as completed.

![2017-04-21_01](https://cloud.githubusercontent.com/assets/223935/25279415/abaf759c-26a6-11e7-826b-ca977ad94b5b.png)

Sample results CSV file:

`
Type,Aggregation Status,Title,Title Language,Description,Description Language,Measure,Ascending,Indicator Title,Indicator Title Language,Indicator Description,Indicator Description Language,Reference Vocabulary,Reference Code,Reference URI,Baseline Year,Baseline Value,Baseline Comment,Baseline Comment Language,Period Start,Period End,Target Value,Target Location Ref,Target Dimension Name,Target Dimension Value,Target Comment,Target Comment Language,Actual Value,Actual Location Ref,Actual Dimension Name,Actual Dimension Value,Actual Comment,Actual Comment Language
1,true,Result zero test,en,,,1,true,Indicator zero test,en,,,99,123,,2016,0,,en,2016-01-01,2016-12-31,0,,,,,,0,,,,,
1,true,Zero point zero,en,,,1,true,Indicator zero point zero test,en,,,99,123,,2016,0.0,,en,2016-01-01,2016-12-31,0.0,,,,,,0.0,,,,,
`

**Comment by sachit-singh** [comment]
Hi.

The target and actual value are shown as 'Not Available' whereas the baseline value is shown as 0 if it is a 0 value. However, if the baseline value is missing, i.e., when there is validation error in the file, the above error is shown.
As long as it passes all the schema and AidStream's Validation rules, there should be no problem.

We tested this with the sample data you have provided, and it is working.

Type,Aggregation Status,Title,Title Language,Description,Description Language,Measure,Ascending,Indicator Title,Indicator Title Language,Indicator Description,Indicator Description Language,Reference Vocabulary,Reference Code,Reference URI,Baseline Year,Baseline Value,Baseline Comment,Baseline Comment Language,Period Start,Period End,Target Value,Target Location Ref,Target Dimension Name,Target Dimension Value,Target Comment,Target Comment Language,Actual Value,Actual Location Ref,Actual Dimension Name,Actual Dimension Value,Actual Comment,Actual Comment Language
1,true,Result zero test,en,,,1,true,Indicator zero test,en,,,99,123,,2016,0,,en,2016-01-01,2016-12-31,0,,,,,,0,,,,,
1,FALSE,Zero point zero,en,,,1,true,Indicator zero point zero test,en,,,99,123,,2016,0,,en,2016-01-01,2016-12-31,0,,,,,,0,,,,,

Would you please confirm and let us know.
Thank you.

**Comment by sachit-singh** [comment]
Hello @rolfkleef 

This issue has been solved. Could you please verify from your side.

Thank you.
