### ISSUE TITLE
Allow Budget Period of more than a year? 

### ISSUE THREAD

**Issue by sachit-singh** [younginnovations/aidstream#96]
According to the standard budget period should not be more than one year. 
Please see http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/budget/period-end/

But it is not the case for most NGOs. Confusion on whether to allow budget with period more than a year.

**Comment by 77karuna** [comment]
Hi Sachit,

Thanks for the concern and bringing this into our attention.
However, for now, let us go in accordance with the IATI Standard. 
In case of changes in the standard in the future, it can be managed accordingly.
Hence, closing this issue.

Regards,
Karuna
On behalf of AidStream Support

**Comment by sachit-singh** [comment]
Sure, no problem @77karuna  ¯\_(ツ)_/¯
