### ISSUE TITLE
Reorder the activity-date attributes in XML

### ISSUE THREAD

**Issue by anjesh** [younginnovations/aidstream#98]
Currently this is how activity-date appears in XML
```
<activity-date type="2" iso-date="2016-01-01"/>
```

It should have been 
```
<activity-date iso-date="2016-01-01" type="2" />
```

Reported by Marten from Akvo.

**Comment by rolfkleef** [comment]
Hi Anjesh, the order of attributes is not important, both forms are fine. [If you look at the schema](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L691-L698), you'll see they're actually defined in the order you now use :-)

**Comment by anjesh** [comment]
Thanks Rolf. I thought so, but schema validated it.
