### ISSUE TITLE
Error 404 - CSV uploaded activities not found

### ISSUE THREAD

**Issue by amy-silcock** [younginnovations/aidstream#99]
I've encountered an error whereby I can't view/edit activities that are listed on my dashboard. These particular activities were uploaded through the CSV import function. They seemed to upload successfully but I then when I try to enter/view/edit them, I get the '404 - something went wrong screen'.

Please can you help sort this.

This is being experienced by a new publisher transitioning from CSV2IATI to AidStream.

**Comment by sachit-singh** [comment]
Dear Amy,

Could you please tell us the organisation into which you had uploaded the Activities?

Sachit.

**Comment by amy-silcock** [comment]
Hi,

I uploaded Oxford Policy Management’s activities into my account to test it.

It’s the account attached to amysilcock@hotmail.com<mailto:amysilcock@hotmail.com>

Best wishes,

Amy

Amy Silcock I IATI Business and Data Analyst
Development Initiatives, North Quay House, Quay Side, Temple Back, Bristol, BS1 6FL, UK
T: +44 (0) 1179 272 505 I Skype: amy.silcock.devinit.org
devinit.org<http://www.devinit.org/> I @devinitorg
Sign up<http://devinit.org/#!/about/newsletter-sign-up> to our newsletter and topic updates

DISCLAIMER: This email and any attachments are confidential and intended solely for the use of the individual or organisation to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Development Initiatives.  If you have received this email in error, please delete it and notify the sender.
